kaltura/playkit-js-ui

src/components/language/language.js
src/components/settings/settings.js

settings menu simplified as product request (no ticket)
filter out video and audio tracks that doesn’t have all required data.

fix: settings menu simplified

---

src/ui-presets/ads.js

fix(FEC-7074): toggle ads ui rules

---

src/components/engine-connector/engine-connector.js
src/components/volume/volume.js

listen to player mute status change and update UI.
depends on https://github.com/kaltura/playkit-js/pull/121

fix(FEC-7182): update UI accorindg to mute status change

---

CHANGELOG.md

chore: fix duplicates in CHANGELOG.md

---

src/components/cvaa-overlay/cvaa-overlay.js

Fixing font style active state after changing from drop menu.

fix: font style active state

---

src/components/cvaa-overlay/_cvaa-overlay.scss
src/components/cvaa-overlay/cvaa-overlay.js
src/components/overlay/_overlay.scss

Accessibility issue of apply button in responsive version of advanced cvaa overlay fix.

fix: cvaa overlay responsive fixes

---

src/components/ad-learn-more/ad-learn-more.js

open clickthrough URL in a separate new tab/window.

fix: open clickthrough in new tab/window

---

src/components/dropdown/dropdown.js
src/components/menu/menu.js
src/components/shell/shell.js
src/components/smart-container/_smart-container.scss

Support of menu long labels without line break

fix(FEC-7236): long menu labels in smart container

---

webpack.config.js

patch: css class prefix change

---

src/styles/_shell.scss

overlay portal z-index should be raised so overlays will be visible in window phone browser

fix(FEC-7252): overlay hidden fix

---

src/components/seekbar/seekbar.js

seekbar element css classes fix after css modules feature added

fix: seekbar css classes update

---

src/components/ad-learn-more/_ad-learn-more.scss

Import the necessary scss classes so the ad-learn-more scss.

fix: ad learn more ui styles

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss

disable accessibility control bars when hidden

fix(FEC-7320): disable accessibility control bars when hidden

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

poster background size change to contain

fix(FEC-7257): poster background size change to contain

---

src/components/language/language.js

Following Preact Portal bug in explorer (https://github.com/developit/preact-portal/issues/2),
implementing the workaround.

fix(FEC-7312): preact portal fix in Explorer

---

src/components/icon/icon.js
src/components/play-pause/play-pause.js
src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

fix(FEC-7349): typo in startover icon

---

src/ui-presets/ads.js

fix: typo of ads ui label

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

disable background repeat for posters.

fix(FEC-7344): repeated poster bug fix

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

This reverts commit d24fca072d0bb059da7b739b9b82012b133fab18.

revert: "fix(FEC-7344): repeated poster bug fix (#111)"

---

src/components/fullscreen/fullscreen.js

1. UI app should notify the player regarding the fullscreen state by calling the player API.
2. UI app should listen to fullscreen requests from the player and change the fullscreen state accordingly.

feat: connect the fullscreen to the player

---

.eslintrc.json
src/ui-manager.js
webpack.config.js

add export of name and version of library.

feat: export name and version on module

---

src/components/cvaa-overlay/_cvaa-overlay.scss

Fix cvaa 'Apply' button css definitions.

fix(FEC-7531): cvaa 'Apply' button shown only on hover with wrong line height

---

src/components/slider/slider.js

Check min and max values on keyboard dragging.

fix(FEC-7538): font/background opacity - possible to move scrubber outside right bar border by press on "arrow" key

---

src/components/shell/shell.js
src/reducers/config.js
src/ui-presets/playback.js

* enable to config the shell component
* consider the shell config whether to show the player as on touch device (mainly for the studio)

feat(shell): enable configure the shell to force ui like on touch device

---

src/components/rewind/rewind.js
src/styles/_control-button.scss

Toggle animation when clicking on rewind button.

feat: animate rewind button

---

src/components/keyboard/keyboard.js
src/utils/key-map.js

* update speed keys shortcuts from `+ - =` to `< > :`
* remove key log from each handler and instead log in one centralized place

fix: update speed keys shortcuts

---

src/components/seekbar/seekbar.js

Add real buffered progress in the seekbar component based on the buffered api of the player.
kaltura/playkit-js#169

feat(FEC-7568): seekbar buffered progress is hard coded

---

src/components/shell/shell.js

adding the shell to the tabbing traversal, changing it tabIndex attribute to 0.

fix(FEC-7591): player shell is not part of the tabbing traversal

---

src/components/error-overlay/error-overlay.js

Retry callback should pass the media info object.

fix: retry callback

---

src/components/error-overlay/_error-overlay.scss
src/ui-presets/error.js

Override overlay class just if error UI is displayed.

fix(FEC-7910): When using the custom captions menu, the video is totally blocked and not blurred

---

src/styles/style.scss

fix(FEC-7921): Slider isn't displayed in CVAA menu

---

src/components/unmute-indication/_unmute-indication.scss

fix(FEC-7932): mute indication text is coloured blue instead of white

---

src/components/menu/menu.js
src/components/shell/shell.js
src/reducers/shell.js

Fix calculation of dropdown positioning to relative to player container.

fix: dropdown position calculation

---

src/components/bottom-bar/bottom-bar.js
src/components/language/language.js
src/components/seekbar-playback-container/seekbar-playback-container.js
src/components/seekbar/seekbar.js
src/components/settings/settings.js
src/components/shell/shell.js
src/components/volume/volume.js
src/reducers/language.js
src/reducers/seekbar.js
src/reducers/settings.js
src/reducers/shell.js
src/reducers/volume.js
src/store.js

fix(FEC-7931): UI flickering on hovering the bottom bar

---

src/components/seekbar-ads-container/seekbar-ads-container.js
src/components/seekbar-live-playback-container/seekbar-live-playback-container.js

fix: console error on ads seekbar hover

---

src/components/engine-connector/engine-connector.js
src/components/error-overlay/error-overlay.js
src/reducers/engine.js
src/ui-presets/error.js

remove the error overlay in SOURCE_SELECTED and AD_BREAK_START

fix(FEC-7971): change media doesn't work after a critical error 

---

src/components/seekbar/seekbar.js
src/components/shell/shell.js
src/components/volume/volume.js

* Discard volume & seekbar controls mouse events on mobiles (causes wrong state in Shell)
* Fix Shell touch handler logic

fix(FEC-7991): when changing captions language, the captions and playbar stay visible all the time

---

src/components/watermark/_watermark.scss

move watermark behind everything

fix: move watermark behind everything

---

docs/configuration.md

Update docs for seekbar component.

docs: seekbar component

---

src/components/fullscreen/_fullscreen.scss
src/components/fullscreen/fullscreen.js
src/styles/_shell.scss

remove bad style for captions and unnecessary style for full screen

fix(FEC-8012): captions on ipad displayed in center

---

src/ui-presets/ads.js

the seek bar is unnecessary while ad, also it takes needed space - removed while ad

fix(FEC-8099): remove the seek bar while ad

---

src/components/overlay-action/overlay-action.js

added logic to support differentiate double click from single click.

feat(FEC-8102): toggle fullscreen on double click

---

README.md
docs/custom-ui-preset.md
docs/guides.md

Update 
* README.md
* configuration.md

docs: update 

---

flow-typed/types/ui-options.js

Causing the kaltura player build to fails.

fix: UI options flow type

---

src/components/seekbar/seekbar.js

Fix incorrect bounded event handler.
Regression from #234

fix(FEC-8214): seekbar playhead cannot be dragged

---

src/components/shell/shell.js

creating a new target object so the shellActions object wont be muted

fix(FEC-8268): the scrubber doesn't moved with the cursor during seek

---

src/components/overlay-action/overlay-action.js

add a threshold of 5 to consider minor movement as click and not as dragging

fix(FEC-8338):  [360][Android] Play/Pause sometimes is not working

---

src/components/engine-connector/engine-connector.js
src/reducers/engine.js

* revert the previous fix for this issue: https://github.com/kaltura/playkit-js-ui/pull/191
* fix by getting config for the engine see https://github.com/kaltura/kaltura-player-js/pull/135

fix(FEC-7971): change media doesn't work after a critical error

---

src/components/unmute-indication/_unmute-indication.scss

fix: unmute color

---

src/ui-manager.js

Before destroy first add the player view to the main container and then re-render it.

fix(FEC-7501):  destroy removes all content under player container including the video element

---

src/components/engine-connector/engine-connector.js
src/components/volume/volume.js

always update `IsEnded` to `false` on `PLAY`

fix(FEC-8269): pre-playback overlay is displayed when loop

---

src/components/seekbar/seekbar.js

added the transformX to the offset calculation

fix(FEC-8503): seekbar virtual position is incorrect when positioned in a container with CSS transform

---

docs/custom-ui-preset.md

Fix missing comma in doc example

docs: fix syntax error

---

src/components/ad-skip/ad-skip.js

since https://github.com/kaltura/playkit-js/pull/288

fix: use 'player.ads.skipAd()' instead of 'player.skipAd()'

---

src/reducers/config.js

**DON'T MESS THE GLOBAL STATE OBJECT!!!**

fix(FEC-8462): Thumbnail scrubber preview is overridden when multiple players are loaded simultaneously

---

src/ui-presets/live.js

add PIP component to live preset

fix: add picture-in-picture to live stream

---

src/translations/en.json

key was missing in the translation file.

fix(FEC-8646): unmute text isn't displayed

---

src/components/engine-connector/engine-connector.js

update `currentTime: 0` on `PLAYER_RESET` because `CHANGE_SOURCE_STARTED` is sometimes too late

fix(FEC-8686): the playlist jumps to the last item (in case setting timeToShow)

---

src/components/icon/icon.js
src/components/icon/icon.scss
src/components/playlist-button/_playlist-button.scss
src/components/playlist-button/playlist-button.js

use opacity for disabled button instead of dedicated icon with gray color

fix: disabled playlist button is black

---

src/components/cast-on-tv/cast-after-play.js
src/components/cast-on-tv/cast-before-play.js
src/components/cast-overlay/cast-overlay.js
src/components/engine-connector/engine-connector.js
src/components/index.js
src/components/play-pause/play-pause.js
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

Fix cast sender ui after update sender with new player events and components.
https://github.com/kaltura/playkit-js-cast-sender/pull/7

fix: cast ui

---

.github/PULL_REQUEST_TEMPLATE.md

chore: fix typo in pull request template

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

update `prePlayback: true` on `AUTOPLAY_FAILED` event

fix(FEC-8747): no play button when auto play failed

---

src/components/playlist-countdown/_playlist-countdown.scss

consider the player breakpoints instead of the screen size

fix(FEC-8750): playlist countdown is not fit to the player size

---

src/components/vr-stereo-toggle/vr-stereo-toggle.js
src/components/watermark/watermark.js
src/ui-presets/live.js
src/ui-presets/playback.js
src/utils/component-config.js

* move the watermark component into the player-gui before the bottom bar component
* use component's static `shouldRender` instead of the generic `shouldRenderComponent`

fix(FEC-8710): watermark covers the playlist countdown

---

src/components/playlist-countdown/playlist-countdown.js

add `next` existence protection

fix: uncaught exception from playlist countdown component

---

src/components/cvaa-overlay/cvaa-overlay.js

fix(FEC-8771): cvaa - background opacity does not have specific class

---

src/components/dropdown/dropdown.js
src/components/smart-container/smart-container-item.js

Changed the attribute to match the current label (the one in props), instead of 'icon.quality'

fix(FEC-8258): captions and audio 'for' attribute is set to 'quality'

---

src/components/cvaa-overlay/cvaa-overlay.js

supporting the change in the font size structure in playkit.

fix(FEC-8572): change the way the player compute text tracks font size

---

src/components/volume/volume.js

Some customers want to have a horizontal volume bar. While they modify the CSS to suit their design, we will add the ability to change the volume if it's horizontal.
The UI will detect if the volume bar is horizontal/vertical.
It will calculate the volume the user chose accordingly.

feat(FEC-8817): support horizontal volume bar

---

src/components/playlist-countdown/playlist-countdown.js
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

* Consider `loop` as `autoContinue`.
* Tapping the large replay button does playlist loop. 
Depends on https://github.com/kaltura/kaltura-player-js/pull/208

feat(FEC-8703): playlist loop

---

docs/components/seekbar/README.md
docs/css-classes-override.md

adding to the css overrides docs about how to create a horizontal volume bar

chor(FEC-8847): docs for horizontal volume bar

---

src/components/volume/volume.js

when the volume is 0, and mute/unmute is clicked - change volume to 0.5t.

feat(FEC-8294): toggle unmute on volume icon click when volume was decreased to zero via dragging

---

src/components/bottom-bar/_bottom-bar.scss
src/ui-presets/ads.js

Revert "feat(FEC-8868): mobile ads preset (#346)"
This reverts commit 3726d7d

chore(FEC-8868): revert FEC-8868

---

src/components/keyboard/keyboard.js
src/components/playlist-countdown/_playlist-countdown.scss

Do not apply seeking using keyboard shortcuts while ad break

fix(FEC-8910): seeking using keyboard shortcuts while ad causes content seeking

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

Add `translate(-50%, -50%)` when the pre-play button is active as well

fix(FEC-8960): need to tap on Play button more than one time in order to start playback on iOS

---

src/styles/style.css

set `transform: translate(-50%, -50%)` in `style.css` as well

fix(FEC-8961): the play button located not in the middle of the player

---

src/components/smart-container/_smart-container.scss

changed the class so it will impact all windows browsers.

fix(FEC-8968): native drop downs on windows chrome does not show the options

---

src/components/copy-button/copy-button.js
src/components/share-overlay/share-overlay.js
src/translations/en.json

Added tooltips and i18n support for copy and email and embed share buttons.

fix(FEC-9005): no tooltip displayed on copy link icon

---

src/components/fullscreen/fullscreen.js
src/components/share/share.scss

default element decided on kaltura player (https://github.com/kaltura/kaltura-player-js/pull/235) instead on UI

fix(FEC-8826): element sent from UI for fullscreen

---

src/components/overlay-action/overlay-action.js

Add checks to avoid errors in LG TV

fix(FEC-9113): ui errors in LG TV

---

src/components/shell/shell.js
src/ui-presets/ads.js

Change every check of device.type to mobile or tablet instead, there are more device types which not relevant.

fix(FEC-9177): Smart TV showed as mobile device

---

src/styles/_captions.scss

add prefix for transform prop on browser which doesn't fully support

fix(FEC-9178): seekbar hide the captions

---

src/styles/_shell.scss

add prefix for browser which doesn't fully support on transform.

fix(FEC-9179): seekbar hide non-linear ads

---

docs/configuration.md
flow-typed/types/log-config.js
flow-typed/types/ui-options.js
karma.conf.js
src/ui-manager.js
src/utils/logger.js

add configuration logger options.
handler to output logs with customize function.
option to remove playerVersion from log.

feat(FEC-9023): More logger options

---

src/components/seekbar/seekbar.js

ACT: event dispatch twice on touchend and click, click & touchend fired and doing the same thing for touch devices.
SOLUTION: handle it only in touchend and fix the getTime for touch devices.

fix(FEC-9079): USER_SEEKED event triggering twice

---

src/components/fullscreen/fullscreen.js

on enter/exit fullscreen, our container should get focus for keyboard events, it won't always be the fullscreen element itself because we want the keyboard events which bound to our container.

fix(FEC-8797): keyboard doesn't work in fullscreen

---

src/components/cast/_cast.scss

`--` directive in Sass doesn't evaluate the variable unless it is explicitly set with hash

fix(FEC-9351): cast button is not visible

---

src/components/shell/shell.js
src/ui-presets/ads.js

add IPad OS under touch devices.

fix(FEC-9362): IPad OS wasn't under touch devices 

---

src/components/dropdown/dropdown.js
src/components/menu/menu.js

reverted onSelect to receive option and not props.

fix(FEC-9382): dropdown menus not working in Portal mode

---

src/components/playlist-countdown/playlist-countdown.js

since `_shouldRender` [moved](https://github.com/kaltura/playkit-js-ui/pull/410/files#diff-0d243c7cd26f0477cec89206d7da18d3R43) from static to the instance, need to check it in `componentDidUpdate`

fix(FEC-9395): playlist countdown works even showing is false

---

src/components/playlist-countdown/playlist-countdown.js

previous check checked only time to show and didn't check duration

fix(FEC-9404): when countdown is still hidden tabbing is possible

---

src/components/index.js

fix(FEC-9401): logo class wasn't exposed

---

src/components/language/language.js
src/components/share/share.js
src/components/smart-container/smart-container.js

This was fixed already in FEC-7312 but removed because it looked unneeded - added a comment to make sure it will not be removed again by mistake

fix(FEC-9409): portal doesn't close in ie11

---

docs/events.md
src/components/event-dispatcher/event-dispatcher-provider.js
src/event/event-type.js
src/middlewares/event-dispatcher.js
src/player-gui.js

dispatch preset changed on player gui

fix(FEC-8984): add preset event

---

src/components/cast/cast.js

player has been moved to props
Solves FEC-7408

fix(FEC-7408): when using navigation with TAB key, the cast icon is not responding

---

src/components/cvaa-overlay/main-captions_window.js
src/translations/en.json

replaced span with text tag and id of new localization
solves FEC-9505

fix(FEC-9505): Add i18n support for custom captions

---

src/components/playlist-countdown/playlist-countdown.js

playlist can be null. moved after should render to avoid

fix: null pointer possible exception

---

src/components/fullscreen/fullscreen.js

fix: fullscreen doesn't response correctly

---

src/components/cast/cast.js

tooltip tag was wrapping the entire button div instead of just the icon inside

fix(FEC-9634): cast button messes bottom bar

---

src/components/menu/menu.js

Missing @withEventManager in previous PR
https://github.com/kaltura/playkit-js-ui/pull/484
Solves FEC-9647

fix(FEC-9647): menu doesnt close in cvaa settings

---

translations/de.i18n.json

fix: add german (de) translation file

---

translations/ar.i18n.json
translations/de.i18n.json
translations/es.i18n.json
translations/fr.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

feat(FEC-9621): translate player labels to default languages

---

src/components/index.js
src/components/smart-container/index.js

added relevant export
solves FEC-10027

fix(FEC-10027): missed export of UI components in V7- SmartContainerItem

---

src/index.js

added preacti18n to the ui exported in KalturaPlayer
solves FEC-10028

feat(FEC-10028): export preacti18n in KalturaPlayer

---

src/components/shell/shell.js

fix(FEC-10121): google translate duplicate texts with Preact

---

src/components/button/button.js
src/components/button/index.js
src/components/cast-on-tv/cast-before-play.js
src/components/error-overlay/error-overlay.js
src/components/forward/forward.js
src/components/fullscreen/fullscreen.js
src/components/index.js
src/components/language/language.js
src/components/picture-in-picture-overlay/picture-in-picture-overlay.js
src/components/picture-in-picture/picture-in-picture.js
src/components/play-pause/play-pause.js
src/components/playlist-button/playlist-button.js
src/components/playlist-countdown/playlist-countdown.js
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
src/components/rewind/rewind.js
src/components/settings/settings.js
src/components/share-overlay/share-overlay.js
src/components/share/share.js
src/components/volume/volume.js
src/components/vr-stereo/vr-stereo.js

When the player is nested within a form when clicking any button that is in the control bar we get redirected to any form referral.

fix(FEC-10144): player causes form submit on button click

---

src/components/bottom-bar/bottom-bar.js
src/components/shell/shell.js
src/reducers/shell.js

This became redundant since #497 
Solves FEC-10173

fix(FEC-10173): bottomBarHoverActive state is unused

---

flow-typed/modules/preact-hooks.js
src/components/video-player/video-player.js
src/index.js

export `preact/hooks` as `preactHooks`

fix(FEC-10241): preact hooks doesn't exported from core

---

docs/with-keyboard-event.md

updating with-keyboard-event md to better explain 'setKeyboardEventToScope' and 'updateIsKeyBoardEnabled'

docs: updating with-keyboard-event md to better explain 'setKeyboardEventToScope' and 'updateIsKeyBoardEnabled'

---

.babelrc
package.json

Needed to add `plugin-transform-spread` (which transforms spread arrays [...foo]) to `.babelrc`.

fix(FEC-10354): Languages and Settings menus failed to be opened by click

---

src/components/picture-in-picture/_picture-in-picture.scss

Fix typo on `picture-in-picture.scss`.

fix(FEC-10392): V3 - Exit from PiP mode icon invisible

---

package.json

Still set NODE_ENV to production since redux relays on it.

fix: remove redux warning message

---

docs/ui-components.md
src/components/player-area/player-area-provider.js
src/components/player-area/player-area.js
src/ui-manager.js
test/src/ui-manager.spec.js
test/src/utils/test-utils.js
yarn.lock

* `UIManager` Exposes `addComponent` api which actually deligates to `PlayerAreaProvider._addNewComponentAndUpdateListeners` method (using _Render-Props_ technique)
* Remove empty array condition for removal flow 
* Extract `Fragment` children since add and remove the component behaves worried when children wrapped by a `Fragment`

feat(FEC-10076): add support for dynamic injection

---

CHANGELOG.md
docs/configuration.md
flow-typed/types/log-config.js
flow-typed/types/ui-options.js
package.json
src/ui-manager.js
src/utils/logger.js

Issue: we bundling a few js-logger on Kaltura player.
Solution: get logger from Kaltura player and add stub whenever we don't get it from Kaltura player.

fix(FEC-10524): stub logger and get logger from Kaltura player.

---

src/components/tooltip/tooltip.js

I added 0.5 sec to the previous delay. I think it is more than enough. There is also the time it fades in...
Solves FEC-10102

feat(FEC-10102): delay the tooltip showing

---

src/components/forward/forward.js
src/components/rewind/rewind.js
src/ui-presets/live.js
src/utils/with-animation.js

Added the new controls to the live preset (only for DVR)
and added some checks in the FF and RW buttons when on the edges to avoid jumps in timeline

feat(FEC-10527): add RW/FF controls to live preset

---

src/components/gui-area/_gui-area.scss
src/components/interactive-area/_interactive-area.scss
src/components/managers/index.js
src/components/managers/managers.js
src/components/overlay-action/_overlay-action.scss
src/components/player-area/player-area.js
src/components/seekbar-live-playback-container/seekbar-live-playback-container.js
src/components/seekbar-playback-container/seekbar-playback-container.js
src/components/seekbar-preview/index.js
src/components/seekbar-preview/seekbar-preview.js
src/components/seekbar-preview/seekbar-preview.scss
src/components/seekbar/_seekbar.scss
src/components/seekbar/seekbar.js
src/components/side-panel/_side-panel.scss
src/components/video-area/_video-area.scss
src/components/video-player/_video-player.scss
src/reducers/seekbar.js
src/styles/_variables.scss
src/styles/style.scss
src/ui-manager.js
src/ui-presets/live.js
test/src/managers.spec.js
yarn.lock

1. Increase the seekbar height on hovering (exclude touch device and tiny player)
2. Redesign the virtual progress indicator 
3. Hide the seekbar preview in tiny player
Solves FEC-10311

feat(FEC-10311): timeline scrubber design update

---

src/utils/logger.js

issue: missing methods and properties for getLogger.
solution: add the stubbing for all the methods and properties.

fix(FEC-10779): add the all JSLogger for stubbing

---

package.json
src/components/button-control/button-control.js
src/components/button-control/index.js
src/components/forward/forward.js
src/components/fullscreen/fullscreen.js
src/components/language/language.js
src/components/picture-in-picture/picture-in-picture.js
src/components/play-pause/play-pause.js
src/components/rewind/rewind.js
src/components/settings/settings.js
src/components/share/share.js
src/components/volume/_volume.scss
src/components/volume/volume.js
src/components/vr-stereo/vr-stereo.js
src/styles/_variables.scss

Create `ControlButton` component and composite it all control buttons components.

fix(FEC-10670): Add missing class names

---

src/components/playback-controls/_playback-controls.scss

fix(FEC-10409): When overlay is displayed - all elements of the player should disappear

---

docs/configuration.md
flow-typed/types/seekbar-config.js
src/components/seekbar-live-playback-container/seekbar-live-playback-container.js
src/components/seekbar-preview/seekbar-preview.js
src/components/seekbar-preview/seekbar-preview.scss
src/components/seekbar/seekbar.js
src/styles/_variables.scss

Move UI to work with thumbnail API instead of thumbnail config.

feat(FEC-10941): Use In-Stream DASH thumbnails on the timeline

---

src/components/ad-skip/ad-skip.js

fix(FEC-11122): chromecast - pre-roll ad failed to be skipped during the casting

---

src/components/ad-notice/_ad-notice.scss
src/components/top-bar/_top-bar.scss

when an ad is playing, the dismiss button is showing but not working.
made all left-controls and right-controls children clickthrough and excepted ad-notice.
Solves FEC-11128

fix(FEC-11128): X button on floating player not working

---

.travis.yml
src/components/engine-connector/engine-connector.js

Issue: dependency failed with node version 16.
Solution: set the node js version to 15 for the build.

build: failed with node version 16, set to node version 15.

---

src/components/share-overlay/share-overlay.js
src/components/share/default-config.js
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fr.i18n.json
translations/it.i18n.json
translations/ko.i18n.json

use Localizer for the share buttons
Solves FEC-11219

fix(FEC-11219): share tooltip not localized

---

translations/ar.i18n.json
translations/de.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

* add Hebrew and Canadian French translations 
* add translations for "pictureInPictureExit" and "qualityAuto" in all langs

feat(FEC-10613): add Hebrew/Canadian French translations for player

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss

Regressing bug due to changes in FEC-11128.
Correct fix:
pointer-events: none on top-bar-area and left / right controls and pointer-events: auto should be applied only on direct children of them.
solves FEC-11359

fix(FEC-11359): playlist - the seekbar over bottom left controls doesn't available for the cursor

---

src/components/copy-button/_copy-button.scss
src/components/error-overlay/_error-overlay.scss
src/styles/_buttons.scss
src/styles/_inputs.scss

fix(FEC-11338): update share ui

---

src/styles/_buttons.scss

Issue: incorrect cursor on borderless button.
Solution: change the cursor to pointer for button borderless
****

fix(FEC-9070): mouse stays as a cursor when hovering over borderless buttons

---

src/components/picture-in-picture/picture-in-picture.js
translations/ar.i18n.json
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

on 'Picture in picture' mode, the tooltip shall be "expand” instead of "Exit pictures in pictures

feat(FEC-10287): on 'Picture in picture' mode, the tooltip shall be "expand” instead of "Exit pictures in pictures"

---

translations/ar.i18n.json
translations/de.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

Incorrect translations for 15/16 languages

fix(FEC-11427): incorrect translations for 15/16 languages

---

flow-typed/modules/kaltura-player-js.js
src/components/cast-on-tv/cast-before-play.js
src/components/cast/cast.js
src/components/cast/index.js
src/components/cast/remote-player-type.js

Add remote player type enum instead of importing from kaltura-player

chore: add remote player type enum

---

src/components/playlist-button/prev-next.js

Add null check for playlist item.
Fixes FEC-11872.

fix(FEC-11872): middle play button remains during play

---

src/components/bottom-bar/_bottom-bar.scss
src/components/bottom-bar/bottom-bar.js

move `SeekBarPlaybackContainer` into the `SeekBar` Area
Solves FEC-11886

fix(FEC-11886): unable to remove SeekBarPlaybackContainer from player

---

src/styles/_variables.scss

Expose new live label color for use in related plugin.
Related PRs:
https://github.com/kaltura/playkit-js-related/pull/5
https://github.com/kaltura/kaltura-player-js/pull/532
Resolves FEC-11981

feat(FEC-11981): Related Entries - p3

---

src/components/engine-connector/engine-connector.js

update `isLive` on `SOURCE_SELECTED`
Solves FEC-12167

fix(FEC-12167): UI updated to live/vod only after some time

---

docs/configuration.md

add seekbar configuration to configuration.md file.
Solves FEC-12231

docs(FEC-12231): add seekbar configuration to MD file

---

src/event/fake-event-target.js

add log when exception happens during event handler.
Solves FEC-12275

fix(FEC-12275): [WEB][UI] Add log when exception happens

---

src/components/live-tag/_live-tag.scss
src/components/seekbar/_seekbar.scss

fix(FEC-11978): Live label style should be updated

---

src/utils/themes-manager.js

live and background colors are not changed while configured
solves FEC-12819

fix(FEC-12819): live and background colors are not changed while configured

---

src/components/cast/_cast.scss
src/styles/_variables.scss

fix(FEC-12837): UI colors - Cast icon is black instead of white

---

src/styles/dynamaic-variables.scss
src/utils/color-format-convertors.js
src/utils/themes-manager.js

fix(FEC-12878): V7 Player visual settings inconsistency

---

src/utils/index.js
src/utils/time-format.js

add functions to time-format.js to support https://github.com/kaltura/playkit-js-share/pull/19
Solves FEC-12916

fix(FEC-12916): share Plugin Keyboard Functionality

---

src/reducers/shell.js

solves FEC-12987
related pr: https://github.com/kaltura/kaltura-player-js/pull/608

fix(FEC-12987): Moderation - Nothing happens once clicking on the on the moderation button - Regression 

---

src/components/seekbar/seekbar.js

fix(FEC-13007); Seek-bar indicator in in incorrect position while right side-panel is open in full screen mode

---

src/ui-presets/img.js

fix(FEC-12979): Image Player - overlay Play/Pause button is displayed on mobile

---

src/components/tooltip/tooltip.js

Displays tooltip when element get focus by keyboard
solves FEC-12726

feat(FEC-12726): Visual labels that appear on hover need to appear on keyboard focus as well

---

src/ui-manager.js

fix(FEC-13029): Custom player colors theme are not inflected in the player while custom preset being used

---

src/components/icon/icon.scss
src/components/language/_language.scss
src/styles/_dropdown.scss
src/utils/themes-manager.js

solves [FEC-13022](https://kaltura.atlassian.net/browse/FEC-13022)
[FEC-13022]: https://kaltura.atlassian.net/browse/FEC-13022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13022): fix link and selection accessibility

---

src/components/player-area/player-areas-utils.js
src/components/shell/shell.js
src/components/side-panel/_side-panel.scss
src/components/top-bar/_top-bar.scss

fix(FEC-12519): Side panels should be overlaid the entire player when player size is "SMALL" (smaller then 480px)

---

src/components/top-bar/_top-bar.scss

fix(FEC-13054): Top bar missing when using YouTube entries

---

docs/ui-components.md

docs(FEC-13049): Update docs

---

src/components/tooltip/tooltip.js

- bugfix
**the issue:**
languages tooltip doesn't disappear after opening the captions menu and clicking outside the button (on another place in the window).
Note- this issue reproduces as well with Settings tooltip.
**root cause:**
the settings and languages buttons are wrapped with `withKeyboardA11y`;
after clicking on the languages button to open the menu, and then clicking on a different element which closes the languages menu, the `_previouslyActiveElement` in `withKeyboardA11y` wrapper is the languages button itself, which the wrapper is calling to focus on; hence, the focus handler in tooltip is being invoked and is showing the tooltip. 
**solution:**
hide the tooltip when clicking outside the component.
Solves FEC-13081

fix(FEC-13081): languages tooltip does not disappear after opening the captions menu and clicking on another place on the window

---

src/components/volume/volume.js
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_tw.i18n.json

add translations to volume component.
Solves FEC-13023

fix(FEC-13023): add translations for volume component

---

src/components/language/_language.scss
src/components/language/language.js
src/components/settings/settings.js
src/reducers/config.js
src/reducers/settings.js
src/styles/style.scss
src/ui-presets/live.js
src/ui-presets/playback.js
translations/ar.i18n.json
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

fix(FEC-13115): Move the Languages menu functionality into the settings menu

---

src/components/event-dispatcher/event-dispatcher-provider.js

Update action names in event dispatcher provider with the names of the new language menu components.

fix(FEC-13159): [WEB] - Local Storage broken - subtitle/ audio are not reused after opening one more time

---

src/components/event-dispatcher/event-dispatcher-provider.js
src/middlewares/event-dispatcher.js

fix(FEC-13185): Regression - ui clicks events are not dispatched

---

src/components/fullscreen/fullscreen.js

focus should be on full screen button after hit enter
Solves [SUP-37634](https://kaltura.atlassian.net/browse/SUP-37634)
[SUP-37634]: https://kaltura.atlassian.net/browse/SUP-37634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-37634): ADA Fullscreen button in V7 focus

---

src/utils/color-format-convertors.js
src/utils/themes-manager.js

solves: https://kaltura.atlassian.net/browse/FEC-13116

feat(FEC-13116): set text contrast color according to base color

---

src/components/index.js
src/components/shell/index.js

solves: https://kaltura.atlassian.net/browse/FEC-13187

fix(FEC-13187): export player size enums

---

src/styles/_dropdown.scss

solves: https://kaltura.atlassian.net/browse/FEC-13258

fix(FEC-13258): menu items focus highlight

---

docs/components/error-overlay/README.md
docs/translations.md
src/components/error-overlay/_error-overlay.scss
src/components/error-overlay/error-overlay.js
src/styles/_buttons.scss
translations/ar.i18n.json
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

Solves: https://kaltura.atlassian.net/browse/FEC-13294

fix(FEC-13294): Custom slate - The error message is not as designed

---

src/components/watermark/watermark.js
translations/en.i18n.json

resolves: https://kaltura.atlassian.net/browse/FEC-13234

fix(FEC-13234): Watermark - screen reader - Unlabelled image is shown on the watermark area

---

src/components/audio-entry-details/audio-entry-details.js

Sanitize text and remove html tags
Resolves FEC-13372

fix(FEC-13372): Player v7| audio player Entry info| info text appear with html tags

---

src/ui-presets/ads.js

fix(FEC-13410): Player gets stuck right after the pre-roll is playing Regression

---

src/reducers/shell.js

feat: expose img preset

---

src/styles/_control-button.scss

solves: https://kaltura.atlassian.net/browse/FEC-13411

fix(FEC-13411): Control buttons styles fix

---

src/components/index.js

solves: https://kaltura.atlassian.net/browse/FEC-13424

fix(FEC-13424): Export components

---

src/components/expandable-text/expandable-text.js

resolves: https://kaltura.atlassian.net/browse/FEC-13509

fix(FEC-13509): propagate event for expandable text

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

hide the start over button when overlay is displayed.
solves [ADA-100](https://kaltura.atlassian.net/browse/ADA-100)
[ADA-100]: https://kaltura.atlassian.net/browse/ADA-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-100): "Start Over" button is not hidden

---

src/components/expandable-text/_expandable-text.scss
src/components/expandable-text/expandable-text.js

solves: https://kaltura.atlassian.net/browse/FEC-13519

fix(FEC-13519): No option to tab navigate to "More" buttons inside Navigation plugin

---

src/components/bottom-bar/bottom-bar.js

fix(FEC-13543) : Handle case of lower bar without controllers

---

.eslintignore
package.json
src/components/player-area/player-area-provider.tsx
src/components/player-area/player-area.tsx
src/middlewares/logger.ts
src/types/index.ts
src/types/kaltura-player-js.d.ts
src/types/ui-component-options.ts
src/types/ui-component.ts
src/types/ui-options.ts
src/ui-manager.tsx
tsconfig.json
yarn.lock

Remove kaltura-player-js dep
**Issue:** kaltura player github `actions faild since it depend on playkit-ui types which in turn depend on kaltura-player... and so on.. and on and on... Jesus Christ...
Apparently it used by e2e tests... 
restored
**Fix:** dependency should not depend on dependent.... (this is also a general rule for life...)
Related Prs: 
https://github.com/kaltura/kaltura-player-js/pull/690

fix(FEC-13632): Divert the kaltura-player-js types to be imported locally and not form node_modules (circular deps)

---

tsconfig.json

fix style lint - webstorm eroor

fix(FEC-9999999): style lint - webstorm eroor

---

package.json
yarn.lock

fix(FEC-13669): Aligning all repos with the latest kaltura-browserslist-config to eliminate different browser target among repos

---

src/types/kaltura-player-js.d.ts

Update kaltura-player local copy types
Related prs:
https://github.com/kaltura/kaltura-player-js/pull/729
https://github.com/kaltura/playkit-js-providers/pull/236

fix(FEC-13671): Update kaltura-player local copy types

---

src/components/icon/icon.tsx

Adding "aria-hidden" to icon's elements
[ADA-490]: https://kaltura.atlassian.net/browse/ADA-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-490): [V7-Acc] SVG icons need to be hidden from screen reader update

---

src/ui-manager.tsx

fix(FEC-13716): enable Redux dev-tool

---

src/styles/dynamaic-variables.scss

update color tokens per design.
[FEC-13598]: https://kaltura.atlassian.net/browse/FEC-13598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FEC-13598): update color tokens

---

src/components/bottom-bar/_bottom-bar.scss
src/components/shell/shell.tsx

- make the player's controls part of a page's tabbing flow.

fix(ADA-190): focus to player controls from outside (FEC-13712)

---

src/components/cvaa-overlay/_cvaa-overlay.scss
src/components/cvaa-overlay/custom-captions-window.tsx
src/ui-manager.tsx
translations/en.i18n.json

1. add caption-alignment option into advanced caption menu:

feat(FEC-13664): Add the ability to configure default alignment of captions on the player

---

src/components/seekbar/seekbar.tsx
src/reducers/seekbar.ts
src/types/reducers/seekbar.ts

Add methods that allows add-remove classnames from seekbar component
**Issue:**
**Fix:**

fix(FEC-13707): Set-remove extra classnames for seekbar

---

src/components/event-dispatcher/event-dispatcher-provider.tsx
src/components/logo/logo.tsx
src/event/event-type.ts
webpack.config.js

Add Events (used by kava analytics)

feat(FEC-13744): [Playkit-UI]: Add Events (used by kava analytics)

---

src/components/cvaa-overlay/_cvaa-overlay.scss
src/components/cvaa-overlay/custom-captions-window.tsx
translations/en.i18n.json

This reverts commit bc7d05539c77aecff54de1d8ef4fde542106f96e.
**Issue:**
**Fix:**

Revert "feat(FEC-13664): Add the ability to configure caption alignment

---

src/components/cvaa-overlay/_cvaa-overlay.scss
src/components/cvaa-overlay/custom-captions-window.tsx
translations/en.i18n.json

Add caption-alignment menu option
**Issue:**
**Fix:**
Resolves https://kaltura.atlassian.net/browse/FEC-13664

feat(FEC-13664): Add the ability to configure caption alignment

---

src/reducers/engine.ts
src/reducers/shell.ts
src/styles/exported.scss

Add 'MiniAudioPreset handling
https://github.com/kaltura/playkit-js-audio-player/pull/18
https://github.com/kaltura/playkit-js-downloads/pull/48

feat(FEC-13728): Add 'MiniAudioPreset handling

---

src/components/index.ts

Export side-panels component
Resolves: https://kaltura.atlassian.net/browse/FEC-13729

fix(FEC-13729): export side panels

---

src/components/cvaa-overlay/cvaa-overlay.tsx
src/components/event-dispatcher/event-dispatcher-provider.tsx
src/event/event-type.ts

Captions product analytics
Resolves: https://kaltura.atlassian.net/browse/FEC-13912
Related PR https://github.com/kaltura/playkit-js-kava/pull/176
**Issue:**
**Fix:**

feat(FEC-13912): Captions product analytics

---

src/components/volume/volume.tsx

**Issue:** computer precision error in decimal numbers
**Fix:** round number

fix(ADA-1063): Volume slider 55.00000000000001% value

---

src/components/tooltip/tooltip.tsx

**Issue:**
**Fix:**
resolves: https://kaltura.atlassian.net/browse/FEC-14023

fix(FEC-14023): add strictPosition property to tooltip

---

src/components/volume/_volume.scss

show volume slider only on focus or hover. However JAWS with virtual cursor can reach volume slider that has height 0 and change volume level
**Issue:**
resolves https://kaltura.atlassian.net/browse/SUP-43378

fix(SUP-43378): volume control bar issue

---

src/components/volume/_volume.scss

Reverts kaltura/playkit-js-ui#903

Revert "fix(SUP-43378): volume control bar issue"

---

src/components/volume/_volume.scss

Reverts kaltura/playkit-js-ui#904

Revert "Revert "fix(SUP-43378): volume control bar issue""

---

src/components/side-panel/side-panel.tsx

The side panel ignores update of player size
resolves: https://kaltura.atlassian.net/browse/FEC-14055

fix(FEC-14055): fix update of side-panel

---

src/components/volume/_volume.scss

**Issue:**
Volume control bar was not meeting color contrast requirements
**Fix:**
Changed the color according to the design received, which is corresponding to the color Tone1: https://www.figma.com/design/8yTuCnuVHLYTFp89w7z05J/%F0%9F%93%BA-Player-v7?node-id=10596-24476

fix(ADA-1400): Changed Volume_Bar design to fit the contrast requirements

---

src/components/play-pause/play-pause.tsx

Reverts kaltura/playkit-js-ui#907

Revert "fix(ADA-1275): When user focuses the player he will be able to play/pause with "space" key"

---

src/components/menu/menu.tsx

Resolves: https://kaltura.atlassian.net/browse/FEC-14111

fix(FEC-14111): add SPACE handler on submenu component

---

src/components/logo/logo.tsx

resolves: https://kaltura.atlassian.net/browse/FEC-14108

fix(FEC-14108): handle keydown on logo component

---

src/components/advanced-audio-desc/advanced-audio-desc.tsx

Use redux store as source of AAD value
Resolves: https://kaltura.atlassian.net/browse/FEC-14096

fix(FEC-14096): AAD toggle

---

src/components/cast-on-tv/cast-before-play.tsx
src/components/cast/cast.tsx

Resolves: https://kaltura.atlassian.net/browse/FEC-14109

fix(FEC-14109): handle keydown on cast button

---

src/components/logo/logo.tsx

When the link is not provided the anchor tag is replaced with a span tag
**Issue:**
The SR was announcing logo as link even when no link was provided
**Fix:**

ADA-1572 - Replace a tag with span when link is missing

---

src/components/bottom-bar/_bottom-bar.scss
src/components/bottom-bar/bottom-bar.tsx
src/components/top-bar/_top-bar.scss
src/styles/_variables.scss

Reverts kaltura/playkit-js-ui#925

Revert "fix(FEC-14080): Accessibility fix for the top bar and the bottom bar"

---

src/components/error-overlay/error-message-provider.ts
translations/en.i18n.json

Add specific message to IP restriction.
part of - https://github.com/kaltura/playkit-js/pull/791, https://github.com/kaltura/kaltura-player-js/pull/846
[SUP-43014]: https://kaltura.atlassian.net/browse/SUP-43014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-43014): [elearning] specified error message for v7 for IP restriction

---

src/components/volume/volume.tsx
translations/en.i18n.json

- Removed slider aria-label from volume button;
- Added aria-description to slider so the user would be informed about slider controls;
**Issue:**
**Fix:**

fix(ADA-1610): Update aria label for volume button

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss
src/styles/_variables.scss
src/styles/exported.scss

Add bar gradients
Handle bar gradients for native captions in safari
Resolves FEC-14080

fix(FEC-14080): Accessibility fix for the top bar and the bottom bar

---

src/components/bottom-bar/_bottom-bar.scss
src/components/bottom-bar/bottom-bar-utils.ts
src/components/bottom-bar/bottom-bar.tsx

1. Calculate/re-calculate width of bottom-panel based on control-elements widths
2. use Flexboxes in bottom panel
Resolves: https://kaltura.atlassian.net/browse/FEC-14095

fix(FEC-14095): bottom bar size calculation

---

translations/ca.i18n.json

Add catalan language (ca) translations
Resolves FEC-14185

fix(FEC-14185): Add Catalan locale to player - Core Side

---

src/components/overlay/overlay.tsx
src/components/smart-container/smart-container.tsx

Add new `pauseOnOpen` property that control playback on overlay open/close
**Issue:**
**Fix:**

fix(FEC-14200): pause when overlay opened

---

src/components/play-pause/play-pause.tsx
src/components/seekbar/seekbar.tsx
src/components/tooltip/_tooltip.scss

issue:
play-pause button is undefined , so we weren't able to perform focus action on the button
solution:
after discussing with @SivanA-Kaltura 
it's better to change the way we reference play-pause button to be able to focus on the button element when it's on bigger player sizes.

fix(ADA-1593): fix focus issue on play-pause button with different player sizes

---

src/components/bottom-bar/bottom-bar.tsx
src/components/time-display/_time-display.scss

resolves: https://kaltura.atlassian.net/browse/FEC-14261

fix(FEC-14261): add center controls to bottom-bar

---

src/components/bottom-bar/bottom-bar.tsx
src/components/time-display/_time-display.scss

Reverts kaltura/playkit-js-ui#965

Revert "fix(FEC-14261): add center controls to bottom-bar"

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

**Issue:**
Large play button doesn't have a good visual when it's focused.
**Fix:**
Make the borders thicker for play/start over buttons.
[ADA-2096]: https://kaltura.atlassian.net/browse/ADA-2096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-2096): [University of Illinois] Player 7 Accessibility Issue: There is not enough visual focus given to items.

---

src/components/shell/shell.tsx

Reverts kaltura/playkit-js-ui#976

Revert "fix(SUP-46391): Player Live Full Screen Bug when browser window is not maximized"

---

src/components/shell/shell.tsx

Reverts kaltura/playkit-js-ui#981

fix(SUP-46391): Player Live Full Screen Bug when browser window is not maximized

---

src/components/advanced-audio-desc/advanced-audio-desc.tsx

fix(FEC-14377): AAD component fix

---

package.json
webpack.config.js
yarn.lock

use new `webpack-common` repo to import `insertStylesWithNonce` function.
related to FEC-14367

use webpack common dependency

---

package.json
yarn.lock

upgrade api-extractor version to 7.51.1

upgrade ai-extractor version

---

package.json
yarn.lock

update ai-extractor version to 7.39.1

update ai-extractor version

---

package.json
webpack.config.js
yarn.lock

revert files from commit 2d97fd5fb385ad68f5a13012163d0daee93e560f:
- yarn.lock
- package.json
- webpack.config.js

revert files

---

src/components/advanced-audio-desc/advanced-audio-desc.tsx
src/components/captions-control/captions-control.tsx
src/components/cast/cast.tsx
src/components/closed-captions/closed-captions.tsx
src/components/picture-in-picture/picture-in-picture.tsx
src/components/vr-stereo/vr-stereo.tsx

This solves https://kaltura.atlassian.net/browse/ADA-1736
**Issue:**
**Fix:**

fix(ADA-1736) - Tooltip strict position

---

src/components/tooltip/tooltip.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2430. 
**Issue:**
**Fix:**

Fix(ADA-2430): Hide Tooltip from screenreader

---

src/components/volume/_volume.scss
src/components/volume/volume.tsx
translations/en.i18n.json

**Issue:** Volume control doesn't reachable with voice control
**Fix:** Add hidden element to move focus on volume control

fix(ADA-2120): volume control a11y voice recognition fix

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
src/components/pre-playback-play-overlay/pre-playback-play-overlay.tsx

resolves: https://kaltura.atlassian.net/browse/FEC-14444
**Issue:**
**Fix:**

fix(FEC-14444): prevent click-through pre-playback overlay

---

src/components/advanced-audio-desc-toggle/advanced-audio-desc-toggle.tsx
src/components/advanced-audio-desc/advanced-audio-desc.tsx
src/components/closed-captions/closed-captions.tsx
src/components/event-dispatcher/event-dispatcher-provider.tsx

resolves: https://kaltura.atlassian.net/browse/FEC-14074
**Issue:**
**Fix:**

fix(FEC-14074): EAD events fix

---

src/components/cvaa-overlay/sample-captions-style-button.tsx
src/utils/popup-keyboard-accessibility.tsx

Resolves https://kaltura.atlassian.net/browse/ADA-2330

fix(ADA-2330): fix focus for CVAA overlay

---

src/components/bottom-bar/bottom-bar.tsx

resolves https://kaltura.atlassian.net/browse/ADA-2701

fix(ADA-2701): hide bottom bar if overlay open to avoid focus issues

---

src/components/bottom-bar/_bottom-bar.scss
src/components/bottom-bar/bottom-bar.tsx

Resolves: https://kaltura.atlassian.net/browse/FEC-14451

fix(FEC-14451): player v 7 quiz entry loads without bottom bar

---

src/components/context-menu/_context-menu.scss
src/components/context-menu/context-menu.tsx
src/components/context-menu/index.ts
src/components/error-overlay/error-overlay.tsx
src/components/overlay-action/overlay-action.tsx
src/ui-manager.tsx
translations/en.i18n.json

- Use the player debugInfo field
- Add a context menu to allow copying the debug info
Related PR: http://github.com/kaltura/kaltura-player-js/pull/965
Resolves FEC-14445

feat(FEC-14445): Add Debug Info Option to the Player

---

src/components/play-pause/play-pause.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2127 updating the aria-label entryName when the metadata gets loaded
**Issue:**
**Fix:**

fix(ADA-2127): Update the aria-label when the metadata is loaded

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2781
**Issue:**
**Fix:**

fix(ADA-2781): Fix fullscreen on enter pre playback play button

---

src/components/cvaa-overlay/main-captions_window.tsx
src/components/cvaa-overlay/sample-captions-style-button.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2785 by updating the ref assignment
**Issue:**
**Fix:**

fix(ADA-2785): Fix keyboard navigation in Advanced captions settings

---

src/components/dropdown/dropdown.tsx
src/components/menu/menu.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2698 making HD be announced
**Issue:**
**Fix:**

Fix(ADA-2698) - Make SR announce HD

---

src/components/top-bar/_top-bar.scss

fixing collision of top-bar's right controls and left controls.

fix(FEC-14483): clipToParent | Upper bar buttons position is off

---

src/components/captions-control/captions-control-mini.tsx
src/components/captions-control/captions-control.tsx
src/components/closed-captions/closed-captions.tsx
src/utils/key-map.ts

Reverts kaltura/playkit-js-ui#1034

Revert "fix(FEC-14449): When CC button display on upper bar outside of more plugins, open it with spacebar \ enter doesnt work"

---

src/components/context-menu/context-menu.tsx
src/utils/key-map.ts

Add a keyboard shortcut to copy debug info to clipboard
Resolves FEC-14512

fix(FEC-14512): As a user I want to be able to retrieve debug info using a keyboard shortcut

---

src/components/cvaa-overlay/drop-down-captions-style.tsx

This solves the focus issue reported here https://kaltura.atlassian.net/browse/ADA-2821
**Issue:**
**Fix:**

Fix(ADA-1821): Fix dropdown focus after selection

---

translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

This contains translations for this https://kaltura.atlassian.net/browse/ADA-2313
Seek 10 seconds backward
Seek 10 seconds forward
**Issue:**
**Fix:**

fix(ADA-2313): Seek controls translation

---

src/components/cvaa-overlay/cvaa-overlay.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2799 by focusing on the Settings button inside the player with ID
**Issue:**
**Fix:**

Fix(ADA-2799): Focus management for Advanced captions

---

src/components/settings/settings.tsx
translations/en.i18n.json

This fixes https://kaltura.atlassian.net/browse/ADA-2881 by adding aria-expanded and customizing the aria-label
**Issue:**
**Fix:**

fix(ADA-2881): Aria-expanded on Settings button

---

translations/it.i18n.json

This corrects the translation for "Volume control" in italian here https://kaltura.atlassian.net/browse/FEC-14467
**Issue:**
**Fix:**

fix(FEC-14467): Volume control italian translation

---

src/components/cvaa-overlay/_cvaa-overlay.scss
src/components/cvaa-overlay/custom-captions-window.tsx
src/components/cvaa-overlay/cvaa-overlay.tsx
src/components/cvaa-overlay/main-captions_window.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2821 making Apply button keyboard accessible. After apply, the focus should go to the button that opened the modal
**Issue:**
**Fix:**

fix(ADA-2821) - Make apply button keyboard accessible

---

src/components/play-pause/_play-pause.scss
src/components/play-pause/play-pause.tsx
src/components/pre-playback-play-overlay/pre-playback-play-overlay.tsx
src/components/seekbar/seekbar.tsx

Reverting https://github.com/kaltura/playkit-js-ui/pull/1029
**Issue:**
**Fix:**

Revert"fix(ADA-2781): Pre playback play focus management"

---

src/components/settings/settings.tsx
translations/en.i18n.json

This solves https://kaltura.atlassian.net/browse/ADA-2905
**Issue:**
**Fix:**

fix(ADA-2905): Remove collapsed/expanded message from label

---

src/components/dropdown/dropdown.tsx
src/components/menu/menu.tsx
src/components/top-bar/top-bar.tsx
src/event/event-type.ts
src/reducers/shell.ts
src/styles/_dropdown.scss

continue to - https://github.com/kaltura/playkit-js-ui/pull/1049
**Issue:**
when dropdown bounding is inside topbar element top most element is not clickable 
**Fix:**
check bounding of menu element against the top bar bounding
[SUP-48894]: https://kaltura.atlassian.net/browse/SUP-48894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-48894): Audio flavor selector bug

---

src/components/bottom-bar/bottom-bar.tsx
src/components/captions-control/captions-control.tsx

Reverts kaltura/playkit-js-ui#1065

Revert "fix(FEC-14475): Advanced captions settings cc bottom fix"

---

src/components/video-player/video-player.tsx
translations/en.i18n.json

This solves https://kaltura.atlassian.net/browse/ADA-2960
**Issue:**
**Fix:**

fix(ADA-2960): Add aria-label to video area

---

src/components/seekbar/_seekbar.scss

fix(ADA-2810): Remove seekbar styling on chapters

---

src/components/fullscreen/_fullscreen.scss

This fixes https://kaltura.atlassian.net/browse/ADA-2921
**Issue:**
**Fix:**

fix(ADA-2921): Add focus indicator to Fullscreen button
