src/components/engine-connector/engine-connector.js

When playing on IOS-Safari ad tag url with only preroll for example, for some reason, IMA SDK does not fire CONTENT_RESUME_REQUESTED event and fires only ALL_ADS_COMPLETED.

fix: remove ads ui on all ads completed event

---

src/components/time-display-ads-container/time-display-ads-container.js

Ads "left timer counts" doesn't present the last second, round up the current time and duration.

fix(FEC-7144): round up the timer values of an ad

---

src/components/settings/settings.js

only add auto option for non progressive playback.
depends on exposing streamType on playkit-js here: https://github.com/kaltura/playkit-js/pull/120.
currently we rely on strings but this should be added as types and constants from player.

fix(FEC-7101): remove auto bitrate option for progressive playback

---

src/components/loading/loading.js
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

If player is preloading media a spinner showing in the background of the pre playback button.
This solution will hides the loading spinner and shows only pre-playback button.

fix(pre-playback-state): hide loading spinner on preloading

---

src/components/language/language.js

PlayKit creates a pseudo off text track when there are text tracks available.
This is for connivance only and it internally just tells PlayKit to call hideTextTrack, but it supports the model of emitting the text track change with the selected track where in case of off option it will properly add it to the event payload instead of just throwing null.
Depends on https://github.com/kaltura/playkit-js/pull/118

feat: use off caption from playkit

---

src/components/seekbar/seekbar.js

On playerPoster change, generate new preview image in seek bar.

fix: generates new preview image on playerPoster change

---

src/components/seekbar/seekbar.js

Adding protection to getFramePreviewImg function

fix: posterUrl empty string protection

---

src/styles/_variables.scss

following the removal of external Google fonts in https://github.com/kaltura/playkit-js-ui/pull/69 we should remove this reference from scss variables

fix: remove unused font family

---

src/components/settings/settings.js

Sort function return value should be -1 | 0 | 1 instead of boolean for cross platform support.

fix(FEC-7152): sorting video tracks by bandwidth bug fix

---

src/styles/_shell.scss

overlay-portal need to have z-index only when overlay active in order to make play overlay accessible.

fix: inaccessible play overlay bug fix

---

src/components/volume/volume.js

mouseup and mousemove event changed from progress bar element to document to support ability to change volume from outside of the volume element only.

fix(FEC-7318): volume bar dragging

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
src/components/shell/shell.js

Following playkit-js changes regarding play promise, in case AUTOPLAY_FAILED event is fired, we will want to show the pre-playback button.
Also, the handling for mobile and desktop is the same from now and no need to separate the cases.

feat(pre-playback-btn): listen to AUTOPLAY_FAILED and cancel autoplay

---

src/components/engine-connector/engine-connector.js

'loadedmetadata' is too early to get duration on ios.
get it on `loadeddata`

fix(FEC-7196, FEC-7200): ios - live icon is not highlighted and scrubber at left

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

@dvh91 
The css in the following PR causes the issue:
https://github.com/kaltura/playkit-js-ui/pull/102

fix: remove pre-playback-button added css

---

src/ui-presets/ads.js

The `useDefaultAdsUi`method always returned false because we didn't sent it the `props` param.

fix(FEC-7275, FEC-7360): hide playkit ads ui on mobile

---

src/styles/_captions.scss

captions overlapping on mobile 'hover'

fix(FEC-7359): captions overlapping on mobile hover

---

src/components/smart-container/smart-container.js
src/components/volume/_volume.scss
src/components/volume/volume.js

adding player class when smart container menu open and using it as a dependency to show volume bar.

fix(FEC-7157): dont show volume bar when smart container open

---

src/styles/_captions.scss

When using native captions (currently on Safari) they should be responsive to the player ui.

fix(FEC-7359): add native caption style

---

src/components/volume/volume.js

If were muting/unmuting the player via the iOS native player, our UI was not updated.
The solution is to set the mute prop also in VOLUME_CHANGE event handler.

fix: mute via iOS native player

---

src/components/settings/settings.js

If there's only one quality option then there's no reason to show quality menu for user selection

fix(settings): hide quality selector in case of only 1 option

---

src/styles/_shell.scss

For some reason Safari adds to his webkit-text-track shadow dom element a class named "visible-controls-bar" which contains unnecessary height like the native controls bar are shown.
Looks like a Safari issue but for the meanwhile this is a fix.

fix: native caption height

---

src/components/live-tag/live-tag.js
src/styles/_shell.scss

Add the live tag to the tabs order.

fix: add live-tag to the tabs order

---

src/components/seekbar-ads-container/seekbar-ads-container.js
src/components/seekbar/seekbar.js
src/ui-presets/ads.js

Seek is not allowed while ad is playing, so check if `props.adBreak` set to true and if this the case don't run logic.
Also general fix is added where we are passing to the seekbar component the correct playerContainer via the ads preset.

fix: disable keyboard seek on ad break

---

src/components/seekbar-live-playback-container/seekbar-live-playback-container.js
src/ui-presets/live.js

After seekbar refactor, we forgot to pass the `playerContainer` to the seekbar component in the live preset.

fix(FEC-7540): head-play/scroller seek is not working properly in regular-default mode in PC

---

src/styles/_inputs.scss

The "select" CSS was not name spaced, causing the player to take over sites "select" CSS selector.

fix(FEC-7561): avoid CSS global name space collision

---

src/styles/_shell.scss

captions container overflows outside of player container, this ensures we don't do it.
The issue is when we move the container when hovering or pausing the player and then we need to sync the bottom bar and captions container views.

fix(FEC-7518): captions container overflows

---

src/styles/_shell.scss

add CSS rule to prevent root div element of player to be outlined.
caused by #147

fix(FEC-7563): prevent user select of root div element

---

src/components/loading/_loading.scss
src/components/loading/loading.js

reverts #133 (commit a5ea06aec6894e0cf8bd984e048480ab384104f9)
due to n issue that is caused when autoplaying with native adapter.

revert(FEC-7368): pause of the spinner when loading an ad

---

webpack.config.js

After changing the namespace to playkit.x need to update the externals root value of playkit core.

fix(webpack): playkit core externals root value

---

src/ui-presets/ads.js

Changed the return element from 'undefined' to return a player wrapper with the unmute component

fix(FEC-7807): no unmute icon on ads on mobile

---

src/components/keyboard/keyboard.js

When scroll is enabled in the page, clicking on SPACE was also perform scrolling down.
Add `preventDefault()` when `onkeydown` event triggered.

fix(FEC-7900): prevent default browser behaviour when using keyboard shortcuts

---

src/components/keyboard/keyboard.js
src/ui-presets/ads.js

Keyboard component was missing in the ads UI.
Another fix that needed to be done is to get the ads state to the keyboard component.

fix(FEC-7578): sound of video started to play, if pause pre-roll Ad using navigation mode

---

src/components/loading/loading.js
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

show pre playback play button as soon as possible and load spinner once clicked
this change is possible since https://github.com/kaltura/playkit-js/pull/193

fix(FEC-7907): No play button when preload and ima plugin

---

src/components/dropdown/dropdown.js
src/components/menu/menu.js
src/components/shell/shell.js
src/reducers/shell.js
src/styles/_dropdown.scss

Previous calculation in `getPosition` of Menu component wasn't good enough and based on the fact that the player is always on the top of the page (which of course we can't assume this).
The new calculation considering the dropdown size with its height and checks if its bigger then the player height. If so, we will open this dropdown to the bottom, else, to the top.

fix(FEC-7922): dropdown in CVAA menu is cut and isn't displayed correctly

---

src/components/slider/slider.js

Stop event propagation in keyboard slide of CVAA menu sliders.

fix(FEC-7930): slide with the keyboard in CVAA menu seeks back and forth the player

---

src/components/loading/loading.js

Hide loading spinner when autoplay failed event is triggered.
Also, get rid of the mobileAutoplay flags since its redundant and doesn't exists in the player.
caused by #156

fix(FEC-7956): When autoplay fails, loading spinner stays in the background

---

src/components/loading/loading.js

If were setting up the player and calling later in the code to loadMedia (or configure with sources) spinner will be showing endlessly (not the best user experience).
So we need to raise up the spinner only when source selected and autoplay is on and exclude the case of an ad break.

fix(FEC-7535): Setting autoplay causes player spinner before loading media

---

src/components/keyboard/keyboard.js

Steps to reproduce:
1. Press <
Expected result:
Player will do nothing
Actual result:
Speed down UI gesture is shown

fix(FEC-7959): speed down ui gesture is shown without pressing shift button

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
src/components/shell/shell.js

Issue occurs because the shell catch any click on it and focused his own element.
Moved the pre playback click logic to the pre playback component.

fix(FEC-7963): native menus are not opened in mobile devices (Android/iOS)

---

src/components/shell/shell.js

Fix regression issue when bottom bar doesn't appears on mobiles when video starts to play.
Change the hover state to start on first playing instead of first play.

fix(FEC-7964): touch while playing on mobiles always pause/resume the video

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

add `pre-playback` class to the player on `ended`

fix(FEC-7992): on replay, hovering causes watermark to move up and down

---

src/styles/_captions.scss

Fixing the css selectors.
The condition `:hover` isn't correct since we need to relay only on the `.hover` state.
When the mouse is hovering the player but the bottom bar disappears, the `:hover` is true what cause the selector to include a wrong style.

fix(FEC-7990): captions do not move down when the bottom bar disappears

---

src/components/shell/shell.js

Previous logic shows the hover state on first time the player started to play.
But when we played entry with `preload=auto` it was still too early since `props.prePlayback` was still has `true` value in `_updatePlayerHoverState` what caused the method to terminate.
Change the implementation to when component did update with changes props from prePlayback to !prePlayback => show the hover state for the first time.

fix(FEC-7964):  after first play the control bar is hidden on touch devices

---

src/components/fullscreen/_fullscreen.scss
src/components/fullscreen/fullscreen.js
src/components/shell/shell.js

* correct listening to native ios full screen changes
* on entering to full screen on tablet set the video dimensions to `auto` instead of `100%`

fix(FEC-8012): captions on ipad displayed in center

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

decrease the `.pre-playback-play-button` `z-index` to `1`

fix(FEC-8024): black screen on replay - ie11

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

call to `forceUpdate` on `AUTOPLAY_FAILED` event, as the ui must be updated

fix(FEC-8108): no playback after preroll - android browser

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss
src/styles/_shell.scss

since z-index exists on the ads container, click on the pre-playback isn't triggered. We can safely remove the z-indexes since the layers are now organised correctly.

fix(FEC-8134): replay fails on iOS for playback with ads

---

src/styles/_shell.scss

on overlay ad  set `z-index: 1` to the ads container

fix(FEC-8142): overlay ad clickthrough doesn't work

---

src/components/engine-connector/engine-connector.js

Add `AD_ERROR` listener in the `engine-connector` component and in case the error is fatal update the ad break state.

fix(FEC-8177): playback UI isn't displayed on fatal ad error when changing media

---

src/components/shell/shell.js

Update the hover state if the transition was from pre playback screen
or after an ad break.

fix(FEC-8205): playback UI isn't disappear after ads on mobile

---

src/components/engine-connector/engine-connector.js
src/components/shell/shell.js
src/components/unmute-indication/unmute-indication.js
src/reducers/engine.js

Save a single state of fallback to muted and use it in shell and unmute-indication components.

fix(FEC-8180): when video starts fallback muted and user select to change media the unmute icon is not displayed although video still muted

---

src/components/shell/shell.js

when mouseleave is dispatched from a click within the div it is listening to - it has null in it's 'toElement'. added this check until google fix there bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=798535

fix(FEC-8121): Sometime captions menu close when changing lang although it's in focus

---

src/player-gui.js
src/ui-presets/live.js
src/ui-presets/playback.js

get `isVr` from `props.state.engine.isVr` instead of from player API

fix(FEC-8368): isVr method throws exception on change media

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss
src/styles/_shell.scss

* No ads UI Until the playback source is loaded
* Ads UI while postroll is unlike while preroll and midroll
show `player-gui` while ad-break

fix(FEC-8421, FEC-8422): Ads UI issues

---

src/styles/_captions.scss

Set the captions offset on hovering to `50px` instead of `60px`. 
Fixed also by https://github.com/kaltura/playkit-js/pull/270

fix: subtitles font size is too small on mobile

---

src/components/engine-connector/engine-connector.js
src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

1. Move the addPrePlayback logic to CHANGE_SOURCE_ENDED event.
2. update isEnded state on play instead on playing.

fix(FEC-8450): after replay no control bar

---

src/components/engine-connector/engine-connector.js
src/components/shell/shell.js
src/components/unmute-indication/unmute-indication.js

when clicking on the unmute indication with the keyboard, it does not disappear.
when clicking with the mouse it does - that's because we have (mouse) click handlers in the UI that makes it happen. 
added a 'clicked' state that saves it, if it was clicked, and re-render accordingly.

fix(FEC-8286): adding click indication to the state

---

src/styles/_buttons.scss

override the player button outline on focus to be none, so it won't be overridden by other CSS

fix(FEC-8273): overriding any focus outline - fix IE black screen issue

---

src/components/engine-connector/engine-connector.js

update `isEnded: false` on `AD_BREAK_START`

fix(FEC-8570): Ads UI in wrong state when change media after ended

---

src/components/engine-connector/engine-connector.js
src/reducers/getters.js

1. Rollback the addition of isEnded to isPlayingAdOrPlayback that caused the issue.
2. Add updates to isPlaying and isPaused on ENDED event.

fix: replay button is missing after postroll

---

src/components/engine-connector/engine-connector.js

Moving the update of `ispictureinpicturesupported` attribute to `'loadeddata'`

fix(FEC-8651): picture in picture icon is missing in safari

---

src/components/engine-connector/engine-connector.js

**issue:** in some browsers the `currentTime` is not updated immediately in change media
**solution:** set `currentTime: 0` on `CHANGE_SOURCE_STARTED`

fix(FEC-8644): the playlist jumps to the last item - safari and FF

---

src/components/playlist-countdown/playlist-countdown.js

prevent countdown for short playback

fix: do not show countdown when it is longer than the playback duration

---

src/components/engine-connector/engine-connector.js
src/components/playlist-countdown/playlist-countdown.js
src/reducers/engine.js

* listen to `PLAYBACK_ENDED` instead of `ENDED`
* revert https://github.com/kaltura/playkit-js-ui/pull/291 since it not needed any more

fix(FEC-8669): countdown skips the postroll

---

src/components/engine-connector/engine-connector.js
src/components/playlist-countdown/playlist-countdown.js
src/reducers/engine.js

**issue:** when seeking `currentTime` could be updated before `SEEKED` event (before `lastSeekPoint` updated)
**solution:** do not update the countdown component while seeking

fix(FEC-8671): sometimes the playlist skip to the next item immediately, with no countdown - safari

---

src/components/fullscreen/fullscreen.js

When entering full screen when PIP mode, the video element stays in PIP (on chrome).
Added a check (`isInPictureInPicture()`) before entering fullscreen in the UI.

fix(FEC-8650):  video continues in PiP window when full screen opened

---

src/components/playlist-button/playlist-button.js
src/components/playlist-countdown/playlist-countdown.js

* `NULL` protection
* Do not render next/prev/countdown when relevant data is missing

fix(FEC-8683): playlist by config, no ui for the second entry and onwards

---

docs/cvaa-override.md
docs/ui-customization.md
src/components/cvaa-overlay/_cvaa-overlay.scss
src/components/cvaa-overlay/cvaa-overlay.js

add classes to the cvaa menu items
background: initial, so it will be in the global style object. background initial will set the background to the default value of the browser.

feat(FEC-8671): add CVAA menu labels/ids to enable external CSS to customize it

---

src/components/vr-stereo-toggle/vr-stereo-toggle.js

add `props.state.engine.isVr` condition

fix: stereo button is shown for non-vr content

---

src/components/playlist-countdown/_playlist-countdown.scss
src/ui-presets/live.js
src/ui-presets/playback.js

Move the watermark and the playlist-countdown outside the player gui and set the css on the playlist countdown which is applied automatically while it was under the player gui.

fix(FEC-8778): no watermark is shown in pre-play presentation

---

src/components/engine-connector/engine-connector.js

Change the prePlayback state on PLAY instead of PLAYBACK_START

fix(FEC-8775): preplayback is not updated if play is requested before media is loaded

---

src/components/shell/shell.js

handle `fallbackToMutedAutoPlay` in `onTouchEnd` also

fix(FEC-8799): video not unmuted by tapping on player or seek by dragging

---

src/components/playlist-next-screen/_playlist-next-screen.scss

use `transform: translate(-50%, -50%)` to center an element

fix(FEC-8781): simplify center ui elements

---

src/components/keyboard/keyboard.js

Change the conditions of the key down\up to comply with use cases when the player.volume is not set lower than 0 and higher than 1.

fix(FEC-8784): can't set the volume to 1 or 0/mute via keyboard

---

src/components/playlist-next-screen/_playlist-next-screen.scss

fix(FEC-8806): playlist - next item screen - the text is not centered

---

src/components/cast-on-tv/_cast-on-tv.scss

fix(FEC-8827): cast button is not centered

---

src/components/cast-on-tv/cast-before-play.js

Do not show `cast-before-play` component on replay

fix(FEC-8827): cast button is redundant and unreachable on replay

---

src/components/top-bar/_top-bar.scss
src/ui-presets/ads.js

Render the default player view also on mobile
Added click-through css so the clicks will propagate to IMA

feat(FEC-8124): render player ads UI (also on mobile) unless configured else

---

src/styles/_captions.scss

When an overlay menu is shown (like the advanced captions menu), the subtitles div is hidden (`display: none`).
When the user changes the style of the captions, we recompute its style.  The computing considers the captions divs, which in this case has no dimensions since it has `display: none`.
Changed it to be `visibility: hidden`, so the div's dimensions will be kept while calculating the new style.

fix(FEC-8846): current caption disappear after changing its style in advanced settings

---

src/components/icon/icon.scss

add drop-shadow to the player icons

fix: icons not shown on a white background

---

src/styles/style.scss

remove `components/icon` import as it already imported via the components

fix: icon style is duplicate

---

src/components/engine-connector/engine-connector.js

when closing the pip with the 'x' button on the window, safari fires a `PRESENTATION_MODE_CHANGED` event. 
listening to this event and checking if the player is in PIP mode or not.

fix(FEC-8852): closing pip window on Mac with Safari the video dose not return to the player

---

src/ui-presets/ads.js

Revert to using a different layout on mobile.
Using different layout on mobile
Adding the `adNotice` tag (`id='advertisement'`)

fix(FEC-8866): 'skip ad' button is covered by the control bar on mobile devices

---

src/components/bottom-bar/bottom-bar.js
src/components/cast-on-tv/cast-after-play.js
src/components/cast-on-tv/index.js
src/components/index.js
src/components/top-bar/_top-bar.scss
src/components/top-bar/top-bar.js

* do not render `BottomBar` and `TopBar` when casting and the player is ended
* re-expose `CastAfterPlay` component for https://github.com/kaltura/playkit-js-cast-sender/pull/14
This reverts part of commit ae87bc9 
* add missing css rule for `TopBar` component

fix(FEC-8768): seeking back on ended doesn't work when casting

---

src/components/menu/menu.js
src/styles/_dropdown.scss
src/ui-presets/ads.js

adding a third option to the menu position.
1. Limit the menu height to 80% of the player height. (`0.8*playerHeight`)
2. Position the menu above the bottom of the player.
3. When it's the lowest menu (e.g. captions) - it is indeed almost at the bottom. if its the upper menu (audio) then it will be more up because the menu position is absolute to the `Dropdown` component.
Before:
After:

fix(FEC-8717): the dropdown is cut on large amount of options

---

src/components/smart-container/smart-container-item.js

in case there is not label supplied (e.g. field does not exist in the localization), the label will return as null. added protection.

fix(FEC-8885): smart menu doesn't open if no label is supplied

---

src/components/unmute-indication/unmute-indication.js

Stop the event from bubbling to the shell component.
The shell component listens to this event as well, and for some reason the unmute there causes the player to pause.

fix(FEC-8888): the playback paused when tap on "unmute" button on Android

---

src/components/smart-container/_smart-container.scss

changed the CSS for the options in IE / Edge. Currently, these menus only appear in the small version of the player.

fix(FEC-8905): default drop-downs options in IE and Edge are not visible

---

src/components/bottom-bar/_bottom-bar.scss
src/components/smart-container/_smart-container.scss
src/ui-presets/ads.js

Description of the Changes
Added fullscreen and volume controls to the IMA mobile preset.
moved everything to the left, so it won't clash with IMA's skip button.
Render the default player view also on mobile
References:
https://github.com/kaltura/playkit-js-ui/pull/334

feat(FEC-8868): mobile ads preset

---

src/components/shell/shell.js

Besides checking for dimension on resize events, check for dimensions on `FIRST_PLAY` event.
this way, if the player is hidden before (with dispaly: none e.g) it will be rendered with it's real width and height when it is playing.

fix(FEC-8903): when loading a player with display: none, the player size class is set to small

---

src/styles/_captions.scss

Change the condition of the `Hover` control bar calculation from `Mobile-safari` to `iOS`
- [V] changes have been done against master branch, and PR does not conflict
- [V] test are passing in local environment

fix(FEC-8926): Subtitles are hidden by the seek bar on none Safari browsers in iOS

---

src/components/loading/_loading.scss

Reduced spinner overlay height, so the bottom bar will be clickable.

fix(FEC-8565): bottom bar is not clickable when the loading overlay is displayed

---

src/components/fullscreen/fullscreen.js

Added an additional condition that will add the `attachIosFullscreenListeners()` method when the` `videoElement` is available. 
- [V] changes have been done against master branch, and PR does not conflict
- [V] test are passing in local environment

fix(FEC-8802): Fullscreen event is not available on iOS after an Ad

---

src/components/overlay/_overlay.scss

change headline size small player settings overlay

fix(FEC-8939): language and settings menu dose not fit player size under 480px

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

adding small player breakpoint for the pre-playback button as well.

fix(FEC-8948): play/pause icons (in middle player) are not changing according to player size

---

src/components/shell/shell.js

the `getBoudingClientRect` returns width: 0 and height: 0 in this case, causing incorrect size class

fix(FEC-8980): size CSS class is incorrect if player is rendered when detached from DOM

---

src/ui-manager.js
src/utils/key-map.js

different key code in firefox for semi colon

fix(FEC-7642): firefox speed selector keyboard shortcut doesnt work

---

src/components/share/share.js

The CSS selector was too general, added the player instance selector prefix to it

fix(FEC-9006): invalid share CSS portal selector

---

src/ui-presets/live.js
src/ui-presets/playback.js

The share component is placed outside of the `player-gui` so player state display modes don't apply to it.
Moving it to be under `player-gui` will ensure it shows like the rest of the controls.
Also added reference to `player` in Live preset for `UnmuteIndication` component which was missing.

fix(FEC-9010): share button shows on preplay screen

---

src/components/share-overlay/share-overlay.js

on iOS it is required to use `setSelectionRange` to select an input.

fix(FEC-9004): share copy link doesn't work on iOS

---

src/components/share/share.js
src/components/smart-container/smart-container.js

See https://github.com/kaltura/playkit-js-ui/pull/95 as it is basically the same issue :-(
Also fixed it for smart container as it will now be rendered on desktops(and hence IE11) when player is very small.

fix(FEC-9003): can't close share overlay on IE11

---

src/components/share/share.scss

on end screen the pre playback overlay hides entire video area.
Use same `hack` as control bar and add z-index: 1
Also added CSS rule to keep button always visible like control bar and not on hover.
I general we need to find something less hacky then z-index dependency between pre-playback overlay and end screen visible controls. will open a separate ticket.

fix(FEC-9011): share button dose not work on end screen

---

src/components/icon/icon.scss
src/components/playback-controls/_playback-controls.scss

drop-shadow css was moved from icons.scss to playback-controls.scss in a manner that the css is now applied only on the middle playback icons

fix(FEC-8937): UI icons rendered oddly in iOS

---

src/components/language/language.js
src/components/settings/settings.js
src/translations/en.json

Added the option to alter the Smart Container titles on`settings` and `languages`

feat(FEC-9029): unable to set the Smart Container titles

---

src/components/seekbar/seekbar.js

seek doesnt work in LG TV. transform stored under browser prefix.

fix(FEC-9111): seekbar doesnt work in LG TV

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

Add prefix for transform which doesn't fully support by some web browsers.

fix(FEC-9122): The replay icon is not aligned in LG TV

---

src/styles/_captions.scss

fix css rule for native caption on ios for non native fullscreen mode

fix(FEC-9014): ios non native full screen seekbar hide the captions

---

src/components/loading/loading.js

Do not show the spinner on `AD_LOADED`
Enables **FEC-9159**

fix(FEC-8509): ima-enablePreloading causes the player spinning before the midroll

---

src/ui-presets/ads.js

following #410 Ads preset is referencing player directly so need to use context.

fix: ads preset fails when using player

---

src/components/volume/volume.js

on every touch device it happened.
**issue** - `click` on volume happened after `touchend` on shell - on non-touch device it'll be `click` on volume component and then `click` on shell - the correct behaviour.
**solution** - add `touchend` event on volume button which will `stopImmediatePropagation` and shell won't get this event. as work in desktop, only `click` event will work

fix(FEC-9375): After unmute volume icon, the volume get unmuted and then returning to unmute state

---

src/styles/_shell.scss

added !important to override "reboot" bootstrap css

fix(FEC-9390): keyboard focus outline not working in menus in test page

---

src/components/volume/volume.js

When focused on the volume button - up / down should open the volume bar and control the volume. player was undefined - fixed

fix(FEC-9391): volume bar doesn't open by pressing on up/down arrows

---

src/components/keyboard/keyboard.js

Add check that active track is not undefined and also that ctrl / alt / shift is pressed also

fix(FEC-9394): "c" shortcut when no active caption track throws exception

---

src/components/shell/shell.js
src/components/unmute-indication/unmute-indication.js
src/components/volume/volume.js

add behaviour of toggle mute on keyboard enter.
Implemented onMouseUp cause click on IMA skip button wasn't bubbled to shell.

fix(FEC-9399): enter didn't do anything on volume button

---

src/components/overlay/overlay.js

added tabindex 0 to the X anchor and keydown enter handling

fix(FEC-9402): x button not accessible with keyboard in overlays

---

src/components/playlist-countdown/playlist-countdown.js
src/reducers/index.js
src/reducers/playlist.js
src/store.js

move the `canceled` to own reduced since `this.state` is reset when switching to ad

fix(FEC-9333): when playing a playlist and closing the countdown window, the next entry starts automatically

---

src/components/playlist-countdown/playlist-countdown.js

Do not update the component by `props.currentTime` if it already updated by `props.isPlaybackEnded`

fix(FEC-9413): when seeking the end of the 2nd entry the playlist skip the 3rd entry (last) and jumps to 1st

---

src/components/volume/_volume.scss

add prefixes for `transform` in volume bar control to fix broken visual behaviour.
remove redundant units.

fix(FEC-9307): volume button broken on LG SDK 2

---

src/components/playlist-countdown/playlist-countdown.js

do not render the component when no duration exists (while loading)

playlist countdown screen displayed for 1-2 sec after the player loaded

---

src/components/playlist-countdown/playlist-countdown.js

do not render the component when no duration exists (while loading)

fix(FEC-9428): playlist countdown screen displayed for 1-2 sec after the player loaded

---

src/components/keyboard/keyboard.js

unable the seeking event from keyboard left right home end to live streams without DVR.

fix(FEC -9356): linear without DVR stream has keyboard event for seeking

---

src/components/shell/shell.js

it'll work on ad which playing on same video tag cause we'll get the correct state of paused.
On different video tags we are getting the state of paused from the main video tag but ad is playing on second one and pause icon still showing so added state of adBreak for this situation.

fix(FEC-9423): Small view on desktop the pause icon remains on screen

---

src/components/seekbar/seekbar.js

when dragging scrubber to 0 it fell back to e.changedTouches which was undefined.
Changed the logic to first use e.clientX if is a number (zero included)
Fixes FEC-9433

fix(FEC-9433): timer on seek preview displayed as NaN:NaN:NaN

---

src/components/video-player/_video-player.scss

added scss selector - when overlay is active blur video player
solves FEC-9491

feat(FEC-9491): blur video when overlay active

---

src/components/play-pause/play-pause.js

**Issue:** ima plays the midroll on `ENDED` asynchronously, so `PLAYBACK_ENDED` fired before `AD_LOADED` and `AD_BREAK_START`.
**Solution:** Hide the replay button while ad break, even `isPlaybackEnded` prop is `true`
(This is for ima vmap. The same issue with ad layout fixed by https://github.com/kaltura/playkit-js/pull/416)
Solves [FEC-9493](https://kaltura.atlassian.net/browse/FEC-9493)

fix(FEC-9493): ima - dragging to the end causes the midroll to play with replay button

---

src/components/engine-connector/engine-connector.js

Do `updatePrePlayback(false)` on `FIRST_PLAY`
Solves [FEC-9511](https://kaltura.atlassian.net/browse/FEC-9511)

fix(FEC-9511): the large play button gets stuck when auto play is failed

---

src/components/overlay/_overlay.scss

change background opacity in the scss
Solves FEC-9522

fix(FEC-9522): overlay background should be with 0.7 opacity

---

src/components/engine-connector/engine-connector.js

Do `updatePrePlayback(false)` on `AD_STARTED`
Solves [FEC-9513](https://kaltura.atlassian.net/browse/FEC-9513)

fix(FEC-9513): endless spinner when auto play is failed

---

src/components/live-tag/live-tag.js
src/components/seekbar-live-playback-container/seekbar-live-playback-container.js
src/components/seekbar/seekbar.js

liveedge is not calculated anymore by a threshold but received from the player
In addition - when in live edge the progress bar duration is the current time
solves FEC-9471

fix(FEC-9471): slider progress bar exceeds 100%

---

src/components/playlist-countdown/playlist-countdown.js

removed setState inside the render function as this causes unexpected behaviour and is considered bad practice. moved to componentDidUpdate
solves FEC-9521

fix(FEC-9521): countdown is stuck open after next video started

---

src/components/menu/menu.js

due to a bug created in FEC-7202 - caused by moving the menu component as child of the dropdown component - both listeners were handled when selecting a menu item.
Added stopPropagation in the menu so the dropdown code will not be handled
solves FEC-9556

fix(FEC-9556): menu remains open after selecting with mouse

---

src/components/playlist-countdown/playlist-countdown.js

commenting out the auto focus
deprecating FEC-9479 for now
solves FEC-9555

fix(FEC-9555): in mobile devices portrait mode when countdown shows the player jumps to the left

---

src/components/playlist-countdown/_playlist-countdown.scss
src/components/playlist-countdown/playlist-countdown.js

Separated the slide from right as an animation and added a listener to animationend to autofocus and to make the component accessible.
In addition, components "next" will be updated only when shown to avoid seeing the next video of playlist when fading out.
solves FEC-9479

feat(FEC-9479): focus on countdown without scrolling issue

---

src/components/cvaa-overlay/_cvaa-overlay.scss

Updated "Edit captions" anchor color in the advanced captions window to support a11y requirements of high contrast
solves FEC-9302

fix(FEC-9302): advanced captions high contrast a11y

---

src/components/volume/volume.js

Issue: overlay indications wasn't set correctly on M key and down arrow key.
Solution: fix the down arrow and muted key overlay indications to be compatible with player state.

fix: overlay indication wasn't fit for keyboard keys

---

src/components/video-player/_video-player.scss

changed blur on video when in overlay from 5px to 16px
solves FEC-9548

fix(FEC-9548): not enough blur on overlay

---

src/components/tooltip/_tooltip.scss

removed unneeded css which ruined safari
solves FEC-9592

fix(FEC-9592): css issue in tooltips in safari

---

src/components/tooltip/tooltip.js

Added a check in the render - if not mobile return children w/o tooltip wrapper
Solves FEC-9595

fix(FEC-9595): tooltip is shown in mobile

---

src/components/seekbar/seekbar.js
src/components/settings/settings.js
src/components/volume/volume.js
src/translations/en.json

Inspired by this PR - https://github.com/kaltura/playkit-js-ui/pull/417
seek bar aria label is hard coded
normal speed text in settings is hard coded
volume - typo in aria-valuemax (is written now aria-valuemaz by mistake)
solves FEC-9604

fix(FEC-9604): some texts were hard coded and not from localization json

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

button tag has a default behavior to fire click event when space bar pressed so change anchor to button.

fix(FEC-9648): space bar doesn't play video on pre-play button

---

src/components/shell/shell.js

caused by the fix done in FEC-9376.
onClick was changed to mouseup. “Enter” or “Space” on Button elements trigger onClick and therefore now don’t effect the unmute. added handling in key down
solves FEC-9601

fix(FEC-9601): when pressing key enter on play button there is no exit from fallback state

---

docs/translations.md

* Change `advertisement` to `ad_notice`
* Fix the `en.i18n.json` link
Solves FEC-9655

docs:(FEC-9655): incorrect key for advertisement in the documentation

---

src/components/settings/settings.js
translations/de.i18n.json
translations/en.i18n.json

add `Auto` to `en.i18n.json` and `de.i18n.json`

fix(FEC-9657): 'Auto' quality option is hardcoded and not translatable

---

src/components/error-overlay/_error-overlay.scss

The css combination on the session div on ie11 caused it to be not visibile.
Fixed as recommended here - https://makandracards.com/makandra/54644-do-not-use-flex-1-or-flex-basis-0-inside-flex-direction-column-when-you-need-to-support-ie11
Solves FEC-7969

fix(FEC-7969): when there is an http error in IE11, the error page is not displaying session ID

---

src/styles/_shell.scss

moved video css to be nested under player-playkit class
solves FEC-9682

fix(FEC-9682): scss preprocessor is not encapsulating 'playkit-' prefix on video controls CSS

---

src/components/shell/shell.js

**Problem**: Once the hovering timeout is done the shell is updating the store with `playerHover:false` which causes a renderer, but at this time the mouse is still hovering the shell so in `onMouseOver` the shell is updating the store with `playerHover:true`, and so on for ever...
(This reproduce in the preact version 8.x (current) only when custom preset is set, but in preactX even with our default presets)
**Solution**: remove the state update from `onMouseOver` as it's redundant since `onMouseMove`
Solves: FEC-9980

fix(FEC-9980): custom preset controls are continuously blinking on hovering the bottom bar

---

src/components/tooltip/tooltip.js

In hindi the letters are higher than English. When put on "left" the tooltip exceeded the bottom and was considered "out of bounds".
Reduced the "safety" margin so this will remain valid also in Hindi
Solves FEC-10018

fix(FEC-10018): in Hindi language, the mute/unmute label is top instead of left

---

src/styles/_shell.scss

add the font-family to `ad-gui-wrapper` class (like `playback-gui-wrapper` has).
Solves FEC-10071

fix(FEC-10071): ad preset is missing the font family

---

flow-typed/types/components-config.js
flow-typed/types/fullscreen-config.js
flow-typed/types/logo-config.js
flow-typed/types/vr-stereo-config.js
src/components/overlay-action/overlay-action.js
src/reducers/config.js

* add `ui.components.fullscreen.disableDoubleClick` config and use it in the overlay-action component
* add missing component config types

feat(FEC-9613): allow application to disable double-click to fullscreen

---

src/components/player-area/player-area.js
src/index.js
src/ui-presets/ads.js
src/ui-presets/error.js
src/ui-presets/idle.js

* Add preset and gui area to all presets
* Support manipulate components (before, after and replace) under Fragment 
* Expose the side panel enums

fix: add preset and gui area to all presets

---

src/components/overlay/_overlay.scss
src/components/overlay/overlay.js

**Issue:** When the player is small (<= `480px`), both language menu and cvaa are opened as an overlay in the `overlay-portal`. This causes 2 issues: 
1. `overlay.position: relative` is inappropriate (pushes the bottom side panel up)
2. `componentDidUnmount` of the language menu is running after `componentDidMount` of the cvaa, and removing a necessary player class (`overlay-active`. so`overlay-portal.pointer-event` remains `none`)
**Solution:** 
1. change to `overlay.position: absolute`
2. delay the `componentDidMount` by timeout

fix(FEC-10227): advanced captions setting window cut when opened in floating player

---

src/components/video-player/video-player.js

1. Move the resize watcher initialization to `componentDidMount`, as before it `iframe.contentWindow` is `null`.
2. Add `id` to `video-player` element for cleaning on destroy

fix(FEC-10229): player failed to be loaded on MAC Safari and IE 11 - Regression

---

src/components/share/share.js
src/components/top-bar/_top-bar.scss

1. Align the top-bar style with the bottom-bar (revert https://github.com/kaltura/playkit-js-ui/commit/02ad5f2b1eeac61d55607333fd62e8b111a0fdee#diff-8603f12b92b47205f68a068e1207dc7aL2 as cannot reproduce its undocumented issue)
2. add to share the missing `controlButtonContainer` class (seems it removed incorrectly in https://github.com/kaltura/playkit-js-ui/commit/935846043cbc6f8337496c515afddab56221359a#diff-10c74714b78c05c56abedc5895abdc5eL96)

fix(FEC-10247): top bar element located in the middle instead of right side

---

src/components/shell/shell.js

Always update the hover state after player transition from paused to playing, whether it's caused by returning from background on mobile or by an API call.

fix(FEC-10052): the bottom toolbar not hiding after return from background on mobile devices

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

hide the bars on pre-playback (as we [did](https://github.com/kaltura/playkit-js-ui/pull/434/files#diff-01d3987c1557ce6ee3ae265e7580484cL35) for `player-gui`)
Solves FEC-10268

fix(FEC-10268): bottom bar displayed before Play button clicked when preload=auto

---

src/components/shell/shell.js
src/utils/with-animation.js

The initial shell mounting is happening after external preset mounts and in tooltips we rely on the shell prop isMobile.
As this is one time decision we can update it in the initial state.
Also refactor our with animation innerRef to avoid passing new anonymous function every time

fix(FEC-10326): customPreset breaks UI

---

src/components/language/language.js
src/components/overlay/overlay.js
src/utils/popup-keyboard-accessibility.js

Bug happens due to focus in the unmount of the KeyBoardAccessibility HOC which occurs before the key event bubbling is done.
- renamed onControlButtonClick to toggleSmartContaierOpen in language.js
- added preventDefault on the key 'enter' to fix the bug and avoid bubbling to the language toggle button
- fixed previouslyActiveElement so it stores only if an auto focus was done and not always - for example - in the languages the menus inside also kept the previous element (which is the same language toggle button) and when the languages were close the button was focused 4 times instead of once

fix(FEC-10226): captions menu doesn't close with keyboard navigation in a small player

---

.babelrc
package.json
src/components/smart-container/smart-container.js

Issue: props didn't pass correctly to the `cloneElement` function, `@babel/plugin-transform-spread` with loose mode make the spinner to not show up.
Solution: use `cloneElement` correctly and remove `@babel/plugin-transform-spread` which isn't needed anymore.

fix(FEC-10472): spinner doesn't show up

---

docs/ui-components.md
src/components/active-preset/active-preset.js
src/components/engine-connector/engine-connector.js
src/reducers/engine.js
src/ui-presets/ads.js

Left controls are shown although the ad is of bumper type.
This caused since the TopBar component isn't rendered again after the ad started.
Adding new state and bind a prop to the ad preset that will trigger a re-rendering after it will update.

fix(FEC-10481): "advertisement" title displays during bumper, when using new Ad layout

---

src/components/keyboard/keyboard.js
src/components/overlay-action/overlay-action.js
src/components/picture-in-picture/picture-in-picture.js
src/components/play-pause/play-pause.js
src/components/seekbar/seekbar.js
src/components/shell/shell.js

Issue: there are multiple timeouts that could be with different timing to handle the disappearing of UI, so there are cases that it makes the wrong behavior.
The new keyboard handler doesn't change the hover state.
Solution: handle UI disappearing in shell only
Change the hover state on new keyboard handler as it was on the previous one.

fix(FEC-10289): controls disappear using keyboard

---

src/components/engine-connector/engine-connector.js

Issue: iOS < 13 doesn't fire `EXIT_FULLSCREEN` when moving from native full screen (AV player) to PiP
Solution: Update the button state using `PRESENTATION_MODE_CHANGED` event
Solves FEC-10526

fix(FEC-10526): iPad iOS11 - wrong full screen button state when PiP active

---

src/components/active-preset/active-preset.js
src/middlewares/logger.js

Issue: logs don't show up.
Solution: create the logger when an instance created.

fix(FEC-10535): activePreset log doesn't show, getLogger called before logger initialised

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss

The bars should be hidden when the overlay is open (to prevent hover toggling)

fix(FEC-10577): the player bars displayed when overlay is open

---

src/components/shell/shell.js

Because the playkit shell has tabIndex and is focusable but doesn't have roles / aria tags then the screen reader is trying to guess the content upon its children.
Before the change it used to say the "Unable to play media" (not sure actually why)
I added aria label "Video Player" and now the screen reader says - "Video Player Group"
Solves FEC-10445

fix(FEC-10445): voice over unable to play media

---

src/components/loading/loading.js

Due to adding "loose": true in "@babel/plugin-transform-spread"
https://github.com/kaltura/playkit-js-ui/blob/master/.babelrc#L31
...Array(8) returns an empty array as it doesn't allow empty spaces in the array

fix(FEC-10660): loading spinner is not showing

---

src/components/share/share.js
src/components/volume/volume.js

Exposed the default tooltip type in Volume and Share as props to be overridden.
solves FEC-10055

fix(FEC-10055): tooltip default position prop should be of the wrapper control instead of the tooltip to enable overriding

---

src/components/cast-on-tv/cast-after-play.js
src/components/cast-on-tv/cast-before-play.js
src/components/copy-button/copy-button.js
src/components/overlay-action/overlay-action.js
src/components/overlay/overlay.js
src/components/tooltip/tooltip.js
src/components/unmute-indication/unmute-indication.js
src/components/watermark/watermark.js

Issue: overlay mounts and unmount immediately then overlayActive class exists.
Solution: clear the timer on unmount to make sure it won't add an overlayActive class after unmount and clear timeout on unmount for all.

fix(FEC-10702): Make sure all timers are cleaned on component unmount

---

src/utils/with-animation.js

In IMA DAI it is first changing to live preset and then to the ad preset causing the forward and backward button to unmount.
Due to changes in:
feat(FEC-10527): add RW/FF controls to live preset
These buttons in non dvr live return undefined in the render so we need to wrap withAnimation with relevant protection in all places. In the original ticket it was protected only in the didMount
Solves FEC-10782

fix(FEC-10782): spinner is shown while Imadai live ad

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.js

Issue: Replay button displayed for half of the second, before the playback started again.
Solution: don't show replay button on the end when loop is enabled, same for the playlist.

fix(FEC-10675): V3 - Replay button displayed for half of seconds after the media finished when loopback enabled

---

src/components/loading/loading.js

Issue: No spinner between the preroll and the playback when disableMediaPreload is true.
Solution: remove the afterPlayingEvent flag to show the spinner before playing the event as expected, no regression from https://kaltura.atlassian.net/browse/FEC-7368 ad_break_start shows the loading state and autoplay_failed remove the loading state.

fix(FEC-10784): No spinner between the preroll and the playback when disableMediaPreload is true

---

src/components/cvaa-overlay/main-captions_window.js
src/components/cvaa-overlay/sample-captions-style-button.js

Issue: we use isEqual method which makes a class property check.
Solution: use the textStyle isEqual API instead.

fix(FEC-10844): advanced caption settings custom caption is always marked even when choose sample

---

src/components/engine-connector/engine-connector.js

Issue: ima post-roll changes `adIsBumper` state to `false` once the pre-roll is loading while the bumper is playing
Solution: Update `adIsBumper` on `AD_STARTED` instead of `AD_LOADED`

fix(FEC-10275): bumper incorrectly recognized as ad

---

src/components/player-area/styles-store-adapter.js
src/components/seekbar/seekbar.js

Issue: The Seekbar mounted after `GUI_RESIZE` already triggered (in imadai event sequence) so the Seekbar dimensions is wrong (0)
Solution: Update the Seekbar dimensions on mounting

feat(FEC-10798): support ima-dai ad breaks cue points

---

src/ui-presets/idle.js

make side panels persistent between medias

feat: allow side panel and player area on the idle preset

---

src/components/cast-on-tv/_cast-on-tv.scss
src/components/cast-on-tv/cast-before-play.js

When page defines margin:auto for divs, cast before play button is not aligned to the center.
css fixes:
1. Remve redundant div.
2. Container div should cover player.
3. Child div should center the button correctly.

fix(FEC-10957): CastBeforePlay button is not aligned to the center

---

docs/configuration.md
flow-typed/types/ui-options.js
src/components/shell/shell.js
src/reducers/config.js

Issue: unable to change our default for hiding the control bar.
Solution: add a new config called controlBarHoverTimeout which will pass the duration of timeout the user wants for this action.

feat(FEC-10667): control-bar auto-hide timeout configuration

---

flow-typed/types/seekbar-config.js

Add `thumbsHeight` definition to seekbar config type.
Note this whole config will be removed after the UI will start to work with new thumbnail API.

feat(FEC-10768): add thumbsHeight to SeekbarConfig

---

src/components/engine-connector/engine-connector.js

Check for cast availability from previous sessions when source is selected.
Solves FEC-10281
Related to https://github.com/kaltura/playkit-js-cast-sender/pull/51

fix(FEC-10281): chromecast does not work after playing it once and trying it on another video

---

src/components/engine-connector/engine-connector.js

Issue: 
1. UI bumper change status on ad_started which could be too late and show the text "advertisement" for a second. 
2. ad_started used because bumper dispatch ad_loaded once before pre-roll for pre-roll and post-roll so with IMA mid-roll it'll keep the advertisement text.
Solution: 
1. add ad_loaded handler to avoid this use case that the status change is too late, ad_loaded will change the status.
2. ad_started shouldn't change the status only on case 2 mentioned above.

fix(FEC-11100): bumper advertisement text appears for second when bumper starts

---

src/components/shell/shell.js

update the player client rect on document.scroll event

fix(FEC-11151): quality dropdown is cropped when user clicks on ‘Quality’ settings on the player after scrolling down

---

src/components/settings/settings.js

Issue: doesn't keep the active flag after changing filtering unique values.
Solution: keep the active flag for the same quality.

fix(FEC-10980): Video tracks selection miss active flag

---

src/components/settings/settings.js

Issue: UI doesn't reflect changes when two bitrates with the same height and the lowest selected.
Solution: always set the active flag if one of them is active to array after filter.

fix(FEC-11260): if set abrEnabled=false, auto mode still remains enabled - HLS

---

src/components/bottom-bar/_bottom-bar.scss
src/components/top-bar/_top-bar.scss
src/styles/_variables.scss

* Moved back Margins to left / right containers instead of padding in the top bar
* Removed padding in bottom bar when not shown and added delay in animation for it not to be visible  while sliding out / in
* Replaced traslate -y in top bar with margin-top because it didn't effect the interactive area
* Reduced top bar and bottom bar appearance / disappearing animation to 100 to match the captions animation. If we to increase it we will need to increase them both.
fixes FEC-11284

fix(FEC-11284): empty top bar fix

---

docs/ui-components.md
src/components/index.js
src/components/player-area/index.js
src/components/player-area/player-area-provider.js
src/components/player-area/player-area.js

Until now it was possible to add new component or to add and replace existing components.
There was no official way to remove an existing ui component.
The new way to that now is to use replaceComponent with the existing component and add the special "remove" string in the get property instead of a new component.
solves FEC-10785
changes were done KP repo also - https://github.com/kaltura/kaltura-player-js/pull/460

feat(FEC-10785): add support to remove ui element

---

src/components/language/language.js
src/components/smart-container/smart-container.js

Issue: document.querySelector doesn't work correctly when element id contains query chars.
Solution: get element by id and make the query.

fix(FEC-11392): document.querySelector breaks

---

src/components/top-bar/_top-bar.scss

When we hide the top bar we put margin-top -60px on it. But if the top bar is empty its height is just 16px and therefore the top bar is moved too high and the interactive area is starting too high also.
The fix is to enforce that when the top is hidden it will be exactly 60px.
I also removed the 16px margin in the children when empty and now it is handled by min-height: 16px
I also fixed some issue caused by css ranking in sm size
solves FEC-11393

fix(FEC-11393): unmute button are cut off when not on hover/there's no top bar

---

src/components/event-dispatcher/event-dispatcher-provider.js
src/components/seekbar-live-playback-container/seekbar-live-playback-container.js
src/components/seekbar/seekbar.js

1. prevent currentTime to be negative
2. add missing event disaptcher case of live seekbar
3. don't use the currentTime and duration from the player but from props

fix(FEC-11419): explore why Live Start over starts with few seconds delay

---

src/components/settings/settings.js

The bottom bar broken for next media in the playlist  
The bottom bar broken, part of the icons don't exist and when click on other, nothing happens
bug: this.props.player.getActiveTracks().video is null when switching between playlist items in settings.js
fix: add check
solves: (FEC-11489)

fix(FEC-11489): V3 - the bottom bar broken for next media in the playlist - regression bug

---

src/components/dropdown/dropdown.js
src/styles/_dropdown.scss

restore the remove css properties in dropdown.scss and fallback label in dropdown.js
fix: FEC-11517

fix(FEC-11517): CVAA - dropdown lists for captions style don't open - regression

---

src/components/active-preset/active-preset.js
src/components/engine-connector/engine-connector.js
src/reducers/engine.js
src/ui-presets/ads.js

Prevent display of bottom bar controls in an ad in case it's not a video ad.
Fixes FEC-10583.
Related PR: https://github.com/kaltura/playkit-js-ima/pull/209

fix(FEC-10583): fix linear image ads

---

src/components/cvaa-overlay/custom-captions-window.js

Use fontSize instead of fontScale.
Fixes FEC-11510.
Related PRs: 
https://github.com/kaltura/playkit-js/pull/603
https://github.com/kaltura/kaltura-player-js/pull/491

fix(FEC-11510): No default font size selected in cvaa

---

src/components/seekbar/seekbar.js

issue : the visibility plugin and seekbar component both listening to mousedown event, while visibility plugin 
which configured by default with draggable true, drag the player element.
fix: stop the mousedown event propagation as long as is fired from seekbar area
solves: FEC-11358

fix:(FEC-11358): Floating player - basic playback - Float window moves while seeking

---

flow-typed/modules/kaltura-player-js.js
src/components/cast-on-tv/cast-before-play.js
src/components/cast/cast.js
src/components/seekbar/seekbar.js

Add call for setIsCastInitiator to mark which in player the cast button was clicked
Fixes FEC-11156
Related PRs:
https://github.com/kaltura/kaltura-player-js/pull/495
https://github.com/kaltura/playkit-js-cast-sender/pull/70

fix(FEC-11156): cast button appears for one player only when multiple players configured on the page and casting failed

---

src/components/cast/_cast.scss
src/components/cast/cast.js

Change cast button styles so that cast button would be highlighted only in actively casting player.
Fixes FEC-11707.

fix(FEC-11707): V3 - cast on multiple players - when casting started by some player, "Cast" buttons become enabled on all players

---

src/styles/_shell.scss

use the same technique like we use to hide the bottom bar and use the css classes representing the player state to toggle the cursor (hide and show it along with the bottom bar)

fix(FEC-11733): Hide mouse cursor when it's idle in fullscreen

---

src/components/index.js
src/components/playback-controls/playback-controls.js
src/components/playlist-button/index.js
src/components/playlist-button/playlist-button.js
src/components/playlist-button/prev-next.js
src/ui-presets/ads.js
src/ui-presets/live.js
src/ui-presets/playback.js

Changes to support related entries grid:
- Refactor next and prev buttons.
- Add PlayerArea for playback controls.
- Export components for use by related plugin.
Fixes FEC-11738.
Related PRs:
https://github.com/kaltura/kaltura-player-js/pull/511
https://github.com/kaltura/playkit-js-related/pull/1

feat(FEC-11738): Related Entries - Phase 1

---

src/components/seekbar/seekbar.js

the seekbar moved (https://github.com/kaltura/playkit-js-ui/pull/653) into the bottom bar area so need to take the offset from its parent
Solves FEC-11933

fix(FEC-11933): if seek with the mouse, the scrubber position doesn't match with the cursor

---

src/components/engine-connector/engine-connector.js
src/components/seekbar-live-playback-container/seekbar-live-playback-container.js
src/components/seekbar-playback-container/seekbar-playback-container.js
src/components/seekbar/seekbar.js
src/reducers/engine.js

hide the progress bar until LOADED_DATA event fired
use `normalizedCurrentTime` and `normalizedDuration` api's
Solves FEC-11922

fix(FEC-11922): Live indicator on progress bar skips back and forward

---

src/components/playback-controls/_playback-controls.scss
src/components/playback-controls/playback-controls.js
src/components/playlist-button/playlist-button.js
src/components/playlist-button/prev-next.js
src/ui-presets/ads.js
src/ui-presets/live.js
src/ui-presets/playback.js

Always show tooltip on overlay playback controls instead of showing preview
Resolves FEC-12154

fix(FEC-12154): Playlist - Active Prev and Next buttons have no tooltip when player width <= 480px

---

src/components/loading/loading.js
src/components/playback-controls/_playback-controls.scss

center playback controls get z-index to let the user pause/play the player during the non-linear vpaid is displayed on small screen - see https://github.com/kaltura/playkit-js-ima/pull/229
also, turn the spinner off when there is no AD_STARTED event but AD_PROGRESS (non-linera vpaid)
Solves FEC-12236, FEC-12237

fix(FEC-12236,FEC-FEC-12237): VPAID ads part of the AD is cut

---

src/utils/with-animation.js

Before https://github.com/kaltura/playkit-js-ui/commit/3b22ffc641969acb3fbef2e97d6a71885630dfa2, when with-animation's componentDidMount was called, the child ref was already set, but the change in the timing of setIsLive caused it to now be null at that point, so it's not possible to register an event listener for child events.
To avoid the issue, I've moved with-animation's event handling into animate, where the child ref is already set.
Resolves FEC-12373

fix(FEC-12373): Web][UI][Chrome][Safari] Seek buttons don't spin after clicking on it for the second time

---

src/components/overlay-action/overlay-action.js

When a user performs a mousedown on the seekbar, and a mouseup on the overlay, and no mousedown event has been fired on the overlay earlier, overlay-action does not detect a drag. This causes the mousedown to toggle the player's play/pause.
The solution was to update the drag detection in isDragging by adding the seekbar drag state.
Resolves FEC-12372

fix(FEC-12372): [WEB][UI] - [O2CZ] Autoplay_WEB - After seeking to the end of the program, the next program will not start playing automatically

---

src/components/engine-connector/engine-connector.js

**issue:** the engine connector is listening to PLAYER.RESET event (which is called on change media)
and switch from 'playback' preset to 'idle' preset which is a totally different UI
**fix:** cancel the switch and remains on the active preset on change media
(i think the 'idle' preset is intended only for player start up)
solves: FEC-12335
related prs:
https://github.com/kaltura/kaltura-player-js/pull/562
https://github.com/kaltura/playkit-js/pull/659

fix(FEC-12335): Side Panel Item gets refreshed in every 'change media'

---

src/components/engine-connector/engine-connector.js

issue: the engine connector is listening to PLAYER.RESET event (which is called on change media)
and switch from 'playback' preset to 'idle' preset which is a totally different UI
fix: cancel the switch and remains on the active preset on change media
(i think the 'idle' preset is intended only for player start up)
solves: [FEC-12335](https://kaltura.atlassian.net/browse/FEC-12335)
related prs:
https://github.com/kaltura/kaltura-player-js/pull/562
https://github.com/kaltura/playkit-js/pull/659

fix(FEC-12335): Side Panel Item gets refreshed in every 'change media' 

---

src/components/dropdown/dropdown.js

Accessibility:
player allow open the internal dropdowns from “Language“ OR “Settings“ elements using space key (and not only from enter key).

fix(FEC-12235): accessibility: Not possible to change items for “Language“ and “Settings“ by space key

---

src/components/volume/volume.js

**the issue:**
when navigating to volume component using the keyboard and pressing up/down arrows (to volume up/down), the entire page is scrolling.
another related issue that was observed- when the volume bar is open via a11y (using keyboard), then clicking anywhere is not closing the volume bar; it should be close in this case.
**root cause:**
we do not prevent from the keyboard event to bubble. when pressing up/down keyboard arrows, the native event scrolls the page.
- preventing from keyboard event to bubble
- closing the volume bar once clicking outside the component
Solves FEC-12517

fix(FEC-12517): [web v7] volume bar arrow keys accessibility

---

src/components/settings/settings.js

added support for RTL languages (Hebrew and Arabic), in the quality label the translate for "Auto" will be RTL.

fix(FEC-12155): RTL languages translation are not supported correctly on the resolution labels

---

src/event/fake-event-target.js

Rename fake-event-target logger to not conflict with children.

fix(FEC-12596): Related plugin doesn't load because of an exception

---

src/components/overlay-portal/overlay-portal.js

add `aria-live=polite` to allow the screen readers to read the content in overlay-portal.

fix(FEC-12772): info content is not readable by screen reader

---

src/components/cvaa-overlay/main-captions_window.js
src/components/cvaa-overlay/sample-captions-style-button.js
translations/ar.i18n.json
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

in "Advanced captions settings" change the button names to Sample 1, Sample 2, Sample 3
solves FEC-12728

fix(FEC-12728): Buttons for caption customization do not have descriptive names (they all say, "sample")

---

src/styles/_plugin-button.scss

Background color of plugin icon should not changed on focus state
solves FEC-12497

fix(FEC-12497): Background color of plugin icon should not changed on focus state

---

src/components/playlist-countdown/playlist-countdown.js

**the issue:**
countdown component shows 10 sec when it shouldn't. see below use-cases:
1. when the player is about to switch to the next media, countdown reaches to 0 and then shows 10 before it disappears.
2. when the countdown comp is rendered (seek to almost the end of the video so it will show for example 7 sec) and performing seeking to a position that the comp should not be rendered (seek to somewhere in the beginning of the video)- countdown shows 10 sec before it disappears.
**solution:**
add a validation to `shouldRender()` func -> check the value of `timeToShow` state.

fix(FEV-1542): countdown shows 10 sec after reaching to 0 and after seeking

---

src/components/active-preset/active-preset.js
src/components/engine-connector/engine-connector.js
src/reducers/engine.js
src/ui-manager.js
src/ui-presets/img.js
src/ui-presets/index.js

solves:  FEC-12612
Add  a new preset for image
related prs: 
https://github.com/kaltura/playkit-js-image-player/pull/1
https://github.com/kaltura/playkit-js-providers/pull/190
https://github.com/kaltura/kaltura-player-js/pull/598
https://github.com/kaltura/playkit-js/pull/697

feat(FEC-12612): Image Playback Options - Fake Video or Single Image Render, and Playlist

---

src/styles/_shell.scss

move the font-family to player class so it will be applied on side-by-side videos.
Solves [FEV-1539](https://kaltura.atlassian.net/browse/FEV-1539)

fix(FEV-1539): inconsistency between the tool tips styles of the dualscreen buttons

---

src/components/cvaa-overlay/main-captions_window.js
src/components/cvaa-overlay/sample-captions-style-button.js
src/components/language/language.js

**the issue:**
current issue is that when navigating to cvaa overlay, the focus should be on the active Sample button, but the focus is actually on a language button element (the globe).
**root cause:**
this happens because the a11yKeyboard wrapper is triggering unmount for the language smart container, after a11yKeyboard didMount for the cvaa overlay.
**solution:**
add useEffect to the sample button component to focus to the active element, once mounted.
In addition, did some minor changes to make sampleCaptions component cleaner.
Solves FEC-12911

fix(FEC-12911): keyboard Navigation - Advanced Captions modal

---

src/components/playlist-next-screen/playlist-next-screen.js

Hide playlist up next screen when autocontinue is true
Resolves FEC-12881

fix(FEC-12881): Inside playlist when autoContinue is true, the square up next video in the middle of the screen is briefly displayed.

---

src/components/logo/logo.js
src/components/watermark/watermark.js
src/styles/_links.scss

when the (click through) url config of watermark and logo components is empty and clicking on them, a new tab is open with the parent url.
The expected behavior is to make these components unclickable, in case the urls are empty.
- change the cursor to `auto` instead of `pointer`
- set `pointer-events` to `none` to prevent the clicks
Solves [FEC-12932](https://kaltura.atlassian.net/browse/FEC-12932)
[FEC-12932]: https://kaltura.atlassian.net/browse/FEC-12932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-12932): watermark, Logo config - When "Click through URL" is empty new tab is open

---

src/ui-manager.js
src/utils/themes-manager.js

**issue:**
In the case of several players on a page, the first player is always colored and **only** the first player is colored.
**solution:**
select the player div element from the dom by the targetId and then select the another elements from the player and not directly from the dom.
solves [SUP-37036](https://kaltura.atlassian.net/browse/SUP-37036)
[SUP-37036]: https://kaltura.atlassian.net/browse/SUP-37036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-37036): Videos not conserving the player customization

---

src/components/volume/volume.js

- bug fix.
**the issue:**
on mobile & web, clicking on the volume control opens the volume bar but it is not possible to close it.
**root cause:**
seems like a regression- original behavior was that on mobiles we do not open the volume bar, while current behavior is opening the volume bar onFocus.
**solution:**
if using mobile- do not allow to open the volume bar onFocus; back to the original behavior.
Solves FEC-13112

fix(FEC-13112): on mobiles web the volume bar stays open once clicking on another area

---

src/components/volume/volume.js
translations/en.i18n.json

a11y fix for volume bar slider.
- volume bar is focusable when tabbing from the volume control button
- when the volume bar is focused, SR is announcing "Volume control, use the arrows to control the volume"
Solves FEC-13188

fix(FEC-13188): volume bar a11y

---

src/components/cvaa-overlay/sample-captions-style-button.js

**the issue:**
in advanced captions settings option, screen reader only reads the name of the buttons and there is no indication whether it checked or not 
**the solution:**
change the role to menuitemradio and add aria-checked attribute 
solves SUP-38236

fix(SUP-38236): Advanced captions settings sample buttons

---

src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss

issue:
on youtube video with quiz the welcome screen didnt display
solution:
add z-index for welcome screen and update z-index for play button so the welcome screen will be show on top on the video

fix(SUP-38205):Youtube IVQ missing welcome screen

---

docs/components.md
docs/components/error-overlay/README.md
docs/translations.md
src/components/error-overlay/_error-overlay.scss
src/components/error-overlay/error-overlay.js
translations/ar.i18n.json
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

Solves: https://kaltura.atlassian.net/browse/FEC-13249
1. New designs for ErrorOverlay component;
2. add `permanent` boolean property to ErrorOverlay that force it render error slate regardless of Kaltura-player error state;
3. add `errorOverlay` configuration to Kaltura-player conf object;

feat(FEC-13249): Customising the “something went wrong” slate

---

src/components/progress-bar.js
src/components/progress-indicator/_progress-indicator.scss
src/components/progress-indicator/index.js
src/components/progress-indicator/progress-indicator.js
src/components/seekbar/_seekbar.scss
src/components/seekbar/seekbar.js
src/reducers/seekbar.js
src/styles/style.scss

part of the Advanced Timeline feature.
this PR contains changes and new code for supporting segments on the seekbar, whenever there are chapters.
- extracting the progress & buffered element to a new comp named ProgressBar
- add new state `segments` to seekbar
- add new actions for updating the segments
**related PR-** https://github.com/kaltura/playkit-js-timeline/pull/11
Solves FEC-13114

feat(FEC-13114): add chapters as segments to seekbar

---

src/components/play-pause/play-pause.js

solves FEC-13118
**issue:**  the keyboard event listener is listening only to events within the player container element scope

fix(FEC-13118):  pause/play playback using keyboard - A11Y issue

---

src/components/quality-menu/quality-menu.js

**the issue:**
in some times, the `videoTracks` state is not getting updated fast enough before rendering the quality menu, which means that not always we have an activeTrack- which causes an error and bad behavior.
**solution:**
adding protection to finding the activeTrack and a fallback to the video track label.
Related to ticket [FEC-13255](https://kaltura.atlassian.net/browse/FEC-13255)
[FEC-13255]: https://kaltura.atlassian.net/browse/FEC-13255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13255): adding protection to active track

---

package.json
src/components/audio-entry-details/_audio-entry-details.scss
src/components/audio-entry-details/audio-entry-details.js
src/components/audio-entry-details/index.js
src/components/engine-connector/engine-connector.js
src/components/expandable-text/_expandable-text.scss
src/components/expandable-text/expandable-text.js
src/components/expandable-text/index.js
src/components/index.js
src/components/scrollable/index.js
src/components/scrollable/scrollable.js
src/components/scrollable/scrollable.scss
src/reducers/engine.js
src/styles/style.scss
src/ui-presets/playback.js
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json
yarn.lock

Add ExpandableText component
Add AudioEntryDetails component
Related PRs:
https://github.com/kaltura/kaltura-player-js/pull/646
https://github.com/kaltura/playkit-js-navigation/pull/334
Resolves FEC-13209

fix(FEC-13209): [Audio Player] adjust full size player UI to entries of audio media type

---

src/components/icon/icon.js

Adding "aria-hidden" to icon's elements
solves [ADA-33](https://kaltura.atlassian.net/browse/ADA-33) 
[ADA-33]: https://kaltura.atlassian.net/browse/ADA-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-33): [V7-Acc] SVG icons need to be hidden from screen reader

---

src/components/cvaa-overlay/custom-captions-window.js
src/components/cvaa-overlay/cvaa-overlay.js
src/components/cvaa-overlay/main-captions_window.js

- Adding role="group" to to div that wraps the samples buttons (and not "menu" since it not working on NVDA).
- Keep the "Advanced captions settings" modal opened also after choosing sample/custom caption. 
solves [ADA-32](https://kaltura.atlassian.net/browse/ADA-32)
[ADA-32]: https://kaltura.atlassian.net/browse/ADA-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-32): [V7-Acc] Add menu on top of menuitems for the advanced captions menu

---

src/components/cvaa-overlay/cvaa-overlay.js
src/components/cvaa-overlay/main-captions_window.js
src/components/overlay/overlay.js
src/components/smart-container/smart-container.js

**issue:**
in advanced captions modal, when open the modal, screen reader reads only : "dialog".
**solution:**
adding aria-labeledby according to the title of the modal so screen reader announce: "Advanced captions settings dialog" 
solves [ADA-31](https://kaltura.atlassian.net/browse/ADA-31)
[ADA-31]: https://kaltura.atlassian.net/browse/ADA-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-31): [V7-Acc] advanced captions modal heading marking correction

---

src/components/play-pause/play-pause.js

**issue:**
focus is moved to the player always when starting play even if the click was not from the user and we was focused on different element.
**solution:**
change the listener from "play to "user click play"
solves [SUP-38805](https://kaltura.atlassian.net/browse/SUP-38805)
[SUP-38805]: https://kaltura.atlassian.net/browse/SUP-38805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-38805): Hero unit causes the page to jump to the top

---

src/components/audio-entry-details/_audio-entry-details.scss

Add explicit line-height to audio entry title and description to prevent external css from overriding these values
Resolves FEC-13373, FEC-13374

fix(FEC-13373): Player v7| audio player entry info| Entry title seem truncated

---

src/components/audio-entry-details/audio-entry-details.js

Audio player details component does not re-render on entry change, probably due to its location in the component hierarchy. 
To force the component to re-render - added a listener to source change events.
Resolves FEC-13377

fix(FEC-13377): Player v7| audio player entry info| Entry info does not change when changing audio entries

---

src/components/audio-entry-details/_audio-entry-details.scss

In KMC preview the position of the backdrop breaks. Added left position to resolve it. 
Resolves FEC-13393

fix(FEC-13393): Player v7| audio player| entry info seem broken in KMC share&embed page

---

src/styles/dynamaic-variables.scss
src/ui-manager.js
src/utils/themes-manager.js

Changes to support audio player colors customization: 
- Add and expose API for working with player CSS variables
- Add new player colors
- Allow configuration of tone 1 and paper colors
Related PR: https://github.com/kaltura/playkit-js-audio-player/pull/10
Resolves FEC-13407

fix(FEC-13407): Slim Audio Player - Allow colors configuration

---

translations/de.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

Adding translation to: “Volume control, use the arrows to control the volume”
solves [ADA-42](https://kaltura.atlassian.net/browse/ADA-42)
[ADA-42]: https://kaltura.atlassian.net/browse/ADA-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-42): i18n Add "Volume Control" Aria Label to the volume slider

---

src/components/volume/volume.js

issue:
when use voiceOver quick navigation can't adjust volume
solution:
add aria-orientation="vertical" to the volume slider

fix(ADA-14):Unable to adjust volume in video player using VoiceOver

---

src/components/volume/volume.js

**issue:**
volume control is not displayed in jaws element list.
**solution:**
remove the role="application" part of [704](https://github.com/kaltura/playkit-js-ui/pull/704) and it's not necessary anymore since we added tabindex on the volume slider.
solves [ADA-5](https://kaltura.atlassian.net/browse/ADA-5)
[ADA-5]: https://kaltura.atlassian.net/browse/ADA-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-5): Volume control is not accessible from element list

---

src/components/logo/logo.js

aria-label was [object object] instead of the strings from the translation object. 
solves [ADA-95](https://kaltura.atlassian.net/browse/ADA-95)
[ADA-95]: https://kaltura.atlassian.net/browse/ADA-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-95): Purpose of logo link on player is not clear in context

---

src/components/forward/forward.js
src/components/rewind/rewind.js

**issue:**
in case props.step is null the label of seek button is "seek backwards/forwards" and not with specific time
**solution:**
use the default step in case of props.step is null 
solves [ADA-111](https://kaltura.atlassian.net/browse/ADA-111)
[ADA-111]: https://kaltura.atlassian.net/browse/ADA-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-111): Seek backwards’ and ‘Seek forward’ labels

---

src/components/volume/volume.js

**issue:**
Volume button command for voice control is not clear enough for the user.
**solution:**
Change the aria-label to "mute" and "unmute" 
solves [ADA-4](https://kaltura.atlassian.net/browse/ADA-4)
[ADA-4]: https://kaltura.atlassian.net/browse/ADA-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-4): Volume control for standard and playlist players are not exposed for Voice Control

---

src/components/bottom-bar/_bottom-bar.scss
src/components/tooltip/_tooltip.scss

- bug fix.
This issue is a regression from this [PR](https://github.com/kaltura/playkit-js-ui/pull/782/files).
**the issue:**
Since the z-index of the seekbar area was increased, it is now overlaying the tooltip of the control buttons which is inside a sibling container of the bottom bar. it also overlays for example the hover container of playlist (next and prev items).
**solution:**
matching the z-index of controls-container to the seekbar.
Solves FEC-13518

fix(FEC-13518): timeline blue bar is on top of button tooltips

---

src/styles/dynamaic-variables.scss

align acknowledgement colors (success, error, warning) with [design](https://www.figma.com/file/8yTuCnuVHLYTFp89w7z05J/%F0%9F%93%BA-Player-v7?type=design&node-id=10596-25297&mode=design&t=PgzlXVLHFVknWO5g-0).
Solves FEC-13573

fix(FEC-13573): align acknowledgement colors with design

---

src/components/settings/settings.tsx

**Issue:**
Audio entries appear with an empty quality menu, because quality menu is populated by the available video tracks
**Fix:**
Hide quality menu for audio entries
Resolves FEC-13556

fix(FEC-13556): Player v7 | Audio player "Quality" button doesn't look good.

---

docs/components.md
docs/components/logo/README.md
docs/configuration.md
src/components/logo/logo.tsx
webpack.config.js

- **enhancement**
allow configuring the `url` configuration with dynamic `entryId` value (for kms).
**for example,** configuring the following url: `https://kms-hostname.com/media/{entryId}`
the entry id will be replaced with the current played entry id (taken from `player.sources.id`), and when clicking on the logo link, it will open the media page in kms.
**Note-** if there is no entry id (for example when using `setMedia` API and not passing the entry id), then the logo will be unclickable.
[FEC-13567]: https://kaltura.atlassian.net/browse/FEC-13567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FEC-13567): add dynamic links to logo

---

src/components/logo/logo.tsx

- **bugfix**
**Issue:**
A use-case where the `medialoaded` event has been fired before logo component was mounted.
in case ima is enabled and the media is being preloaded, listening to `medialoaded` event happens too late (after it was already fired). This is causing not replacing the `{entryId}` in the url, which breaks the url href of the logo.
**Fix:**
before listening to `medialoaded` event, first check if the entry id already exists.
[FEC-13680]: https://kaltura.atlassian.net/browse/FEC-13680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13680): handle logo link with ima

---

src/components/play-pause/play-pause.tsx

**Issue:**
When click on the small play button in the control bar via keyboard, the focus move to playerContainer instead of stay of the play button.
**Fix:**
Check only if the play was done from the large player move the focus to playerContainer(if user click and this is the first play)
[ADA-97]: https://kaltura.atlassian.net/browse/ADA-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-97): The small play button loses the focus after play

---

src/components/side-panel/_side-panel.scss
src/components/side-panel/side-panel.tsx

**Issue:**
If for element uses `position: absolute` and `overflow: hidden` - all child content with absolute position will limited by the element sizes. That causes issue for tooltips and popups that should overlap parent elements (regardless of size).
**Fix:**
1. use `overflow: hidden` for child of element that uses `position: absolute`, so all relative children nodes will be limited by parent size and absolute children will not.
2. use z-index only for small player size (when side panels should take all player area and overlap the player controls).

fix(FEC-13174): fix z-index and overflow of side panels

---

src/components/cvaa-overlay/main-captions_window.tsx
src/components/overlay/_overlay.scss

**Issue:**
The heading for the modal dialog "Advanced captions settings" header is not recognized as header by the screen reader
**Fix:**
Change the the div to h2 element.
[ADA-496]: https://kaltura.atlassian.net/browse/ADA-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-496): The heading for the modal dialog uses implicit CSS (bold text and margin) to indicate headings

---

src/components/smart-container/smart-container.tsx

**Issue:**
The elements in the drop-down menu inside the settings button (such as quality, captions, etc) have a "menuitem" role but are not wrapped in a menu role.
**Fix:**
Adding "menu" role on div inside the settings button.
[ADA-126]: https://kaltura.atlassian.net/browse/ADA-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-126): Certain ARIA roles must be contained by particular parents

---

src/components/shell/shell.tsx

**Issue:**
When user open modal with keyboard, focus is moving to the first element but there is no blue border around the element.
**Root cause:**
The playkit-nav class (that have the css with the border) is removed from the player on mouseOver event.
mouseOver event is triggered also when the mouse enter to the element bounding without move the mouse so when the overlay div is created the mousseOver is triggered.
**Fix:**
Move the functionality to mouseMove event.
[ADA-101]: https://kaltura.atlassian.net/browse/ADA-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-101): There is no indication to the focused element when modal is opened

---

src/components/logo/logo.tsx
src/components/play-pause/play-pause.tsx

use role 'application' to set JAWS screen reader into 'forms' mode, where keys are passed through to the web-page.
**Issue:**
**Fix:**

fix(ADA-190): Focus back on the player from other elements

---

src/components/captions-menu/captions-menu.tsx

**enhancement.**
- sort the languages in the captions menu in an alphabetic order
- keep `Off` language at the end of the list

feat(FEC-13835): sort captions menu in alphabetic order

---

src/components/captions-menu/captions-menu.tsx

Close captions order alphabetically works only for labels that starts with capital letter.

fix(FEC-13897):  Close captions order alphabetically works only for labels that starts with capital letter.

---

src/components/tooltip/_tooltip.scss

**Issue:**
When hovering on controls tooltip is displayed, when you try to move the mouse inside the tooltip area the tooltip disappear.
**Fix:**
Adding inset around the tooltip so user can move inside the tooltip before it disappear.
[ADA-492]: https://kaltura.atlassian.net/browse/ADA-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-492): Low vision users or users requiring screen to be magnified will have difficulties to read through the additional information presented

---

src/components/captions-menu/captions-menu.tsx
src/components/settings/settings.tsx

**Issue:**
enable and disable the caption is no longer working with C shortcut
**Fix:**
move the logic from caption-menu to setting component and add registration under componentDidMount
[SUP-42354]: https://kaltura.atlassian.net/browse/SUP-42354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-42354): shortcut key for enabling/disabling captions

---

src/components/top-bar/_top-bar.scss

- bugfix.
set `visibility: hidden` to top bar component in case left and right controls do not contain any children (top bar is empty).
related PR: https://github.com/kaltura/playkit-js-ui-managers/pull/53

fix(FEC-13709): remove player top bar if there is no content in it

---

src/styles/dynamaic-variables.scss
src/styles/exported.scss

**Issue:**  opacity element of css color of Hex format can not dynamically be changed 
**Fix:** expose the tone ramp global vars as rgb values which can be manipulated dynamically using built-in rgba() css funciton (i.e. :   `background-color: rgba(255 255 255, 0.1);)`
Related Prs:
https://github.com/kaltura/playkit-js-share/pull/44
https://github.com/kaltura/playkit-js-downloads/pull/52

fix(FEC-13880): Add css dynamic vars to support light theme

---

src/components/audio-entry-details/_audio-entry-details.scss

issue:
on audio track when title is not trimmed there is black cover on all screen
fix:
change css in case audio-entry-expanded so the black cover will be only on the title

fix(SUP-41568): Thumbnail dimmed for audio track in V7

---

src/components/volume/volume.tsx

**Issue:**
**Fix:**
Resolves: https://kaltura.atlassian.net/browse/FEC-13949

fix(FEC-13949): a11y labels on volume control

---

src/components/volume/_volume.scss
src/components/volume/volume.tsx

Use opacity to hide/show volume control slider
**Issue:**
**Fix:**
resolves: https://kaltura.atlassian.net/browse/FEC-13973

fix(FEC-13973): volume control a11y changes

---

src/components/picture-in-picture/picture-in-picture.tsx
translations/ar.i18n.json
translations/de.i18n.json
translations/en.i18n.json
translations/es.i18n.json
translations/fi.i18n.json
translations/fr.i18n.json
translations/fr_ca.i18n.json
translations/he.i18n.json
translations/hi_in.i18n.json
translations/it.i18n.json
translations/ja.i18n.json
translations/ko.i18n.json
translations/nl.i18n.json
translations/pt_br.i18n.json
translations/ru.i18n.json
translations/zh_cn.i18n.json
translations/zh_tw.i18n.json

**Issue:**
Aria-label and tooltip of exit picture in picture button are not the same
**Fix:**
Change the tooltip from "Expand" to "Exit picture in picture"
[ADA-1121]: https://kaltura.atlassian.net/browse/ADA-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1121): Exit Picture in Picture labeled as Expand

---

src/components/bottom-bar/_bottom-bar.scss
src/components/icon/icon.scss
src/components/time-display/_time-display.scss
src/components/top-bar/_top-bar.scss

**Issue:**
menu controls can have very low contrast ratios
**Fix:**
make the gradient stronger and add a shadow to the icons and the text
[ADA-1084]: https://kaltura.atlassian.net/browse/ADA-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1084): Color contrast of v7 player icons

---

src/components/settings/settings.tsx
src/components/speed-menu/speed-menu.tsx
src/utils/index.ts
src/utils/key-map.ts

Please add a detailed description of the change, whether it's an enhancement or a bug fix.
**Issue:** Shift+</>  was not working since the events registrations were done inside the speed-menu comp which does not exist until the menu and the submenu are pressed/navigated 
**Fix:** Move the event listener to the parent (settings ) comp which is always existing on the UI

fix(ADA-1296): [ACE] V7 Player keyboard accessibility not working properly

---

src/components/expandable-text/expandable-text.tsx

fix(FEC-14027): ExpandableText Comp fire onExpand on comp init even though was not clicked by the user

---

src/utils/popup-keyboard-accessibility.tsx

Adding boolean var to check if push to the beginning or to the end. part of - https://github.com/kaltura/playkit-js-info/pull/101
[ADA-1335]: https://kaltura.atlassian.net/browse/ADA-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1335): Accessibility- “Close” button within the info video panel.

---

karma.conf.js
package.json
src/components/advanced-audio-desc/advanced-audio-desc.tsx
src/components/bottom-bar/_bottom-bar.scss
src/components/bottom-bar/bottom-bar-registry-manager.ts
src/components/bottom-bar/bottom-bar.tsx
src/components/bottom-bar/index.ts
src/components/captions-control/captions-control-mini.tsx
src/components/captions-control/captions-control.tsx
src/components/closed-captions/closed-captions.tsx
src/components/engine-connector/engine-connector.tsx
src/components/picture-in-picture/picture-in-picture.tsx
src/components/scrollable/scrollable.tsx
src/components/tooltip/_tooltip.scss
src/components/tooltip/tooltip.tsx
src/components/top-bar/_top-bar.scss
src/components/vr-stereo/vr-stereo.tsx
src/reducers/bottom-bar.ts
src/reducers/index.ts
src/reducers/settings.ts
src/store.ts
src/styles/_variables.scss
src/types/reducers/bottom-bar.ts
src/types/reducers/root-state.ts
src/ui-presets/live.tsx
src/ui-presets/playback.tsx
tests/e2e/bottom-bar-registry-manager.spec.js

**New requirement:**
if there is not enough space for controls in bottom bar, instead of removing them- move them to the upper bar.
This was requested for A11y purposes.
- keep 10sec FWD and BWD controls in bottom bar (do not remove them)
- new service to register relevant core components
- new redux state to update the controls that need to be moved from bottom bar to upper bar
- new interface that registers the components to the new service
- a special implementation for `TimeDisplay` component (different behavior)
related PR: https://github.com/kaltura/playkit-js-ui-managers/pull/59

feat(FEC-13945): move core controls to upper bar

---

src/components/scrollable/scrollable.scss
src/components/scrollable/scrollable.tsx

bugfix - regression.
**Issue:**
recent changes in `scrollable` component have caused `More` dropdown to not change its height dynamically.
the root cause is the new `height` style that was added, which exists in cases where it shouldn't.
**Fix:**
- make an accurate calculation to check if there is enough space for the scrollable items inside the parent's container
- set `height` and remove `height` style according to the calculation

fix(FEC-14059): fix the height of scrollable component

---

src/components/fullscreen/fullscreen.tsx

**Issue:**
Holding "enter" on a full screen button will trigger that button repeatedly and causes flashing.
**Fix:**
Check if the event trigger repeatedly by event.repeat and allow enter and exit from full screen only when pressing enter and not when holding the enter.
[ADA-1468]: https://kaltura.atlassian.net/browse/ADA-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1468): Holding Enter on Player Controls Causes Flashing

---

src/components/settings/settings.tsx
translations/en.i18n.json

**Issue:**
When the quality is HD/4k/8k, there is quality icon on the settings button, but there is no indication for screen reader users to the quality state.
**Fix:**
Add additional string to the aria-label to inform about the quality.
[ADA-1383]: https://kaltura.atlassian.net/browse/ADA-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1383): [Strategic Blue / University of Sheffield] - HD label on V7 player Settings button

---

src/components/captions-menu/captions-menu.tsx
src/components/menu/menu.tsx

**Issue:**
The "Advanced captions settings on captions menu has role="menuitemradio" but the option cannot be checked.
**Fix:**
Change role to "menuitem" so that the SR will not announce the option as a checked/not checked option.
[ADA-1062]: https://kaltura.atlassian.net/browse/ADA-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1062): Change role on Advanced captions settings

---

src/components/cvaa-overlay/cvaa-overlay.tsx
src/components/cvaa-overlay/main-captions_window.tsx
src/components/overlay/overlay.tsx

**Issue:**
Accessibility change that was required for announcing the dialog according to it's title.
**Fix:**
Added aria-labelledby to associate the dialog with the descriptive title, improving accessibility for screen reader users.
[ADA-1065]: https://kaltura.atlassian.net/browse/ADA-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADA-1065-Added aria-labelby attribute to the dialog

---

src/components/play-pause/play-pause.tsx

**Issue:**
After the pre-playback-overlay is rendered, with the centered big play button shown in the player container, the user can use it to start the playback and make the overlay component disappear. Afterwards he can play/pause the media by pressing "Space" key due to the fact that initially the play/pause button is focused.
The issue appears when the user switches focus from the player and returns to it, because the play button will not be focused anymore.
**Fix:**
Added event listener on the player container for the space key.

fix(ADA-1275): When user focuses the player he will be able to play/pause with "space" key

---

src/components/logo/logo.tsx

For the Logo link the SR was not announcing a meaningful description. The code was modified so that the message announced can now be customized by the client by modifying the Logo Title.
**Issue:**
Logo link aria-label is not meaningful
**Fix:**
Logo link aria-label is equal to the logo title or absence with a default title

ADA-1499 - Make aria label equal to logo title

---

src/components/settings/settings.tsx

**Issue:** The listener target was on internal comp
**Fix:** listen on document

fix(/ADA-1296): The 'C' keypress  show/hide the Captions only when player clicked with mouse but not when navigated with tabs

---

src/components/bottom-bar/_bottom-bar.scss
src/components/bottom-bar/bottom-bar.tsx
src/components/top-bar/_top-bar.scss
src/styles/_variables.scss

When top and bottom bars are visible, use playkit-video-filter div to show a gradient
Related PRs:
https://github.com/kaltura/playkit-js/pull/790
https://github.com/kaltura/playkit-js-dual-screen/pull/150
Resolves FEC-14080

fix(FEC-14080): Accessibility fix for the top bar and the bottom bar

---

src/utils/popup-keyboard-accessibility.tsx

I'm testing if the previouslyActiveElement exists and I've added a slight delay so that it can be focused on closing the modal 
**Issue:**
On closing, the focus was not going to the button that opened the modal
**Fix:**

fix(ADA-1451): Manage focus on closing info modal

---

src/components/expandable-text/expandable-text.tsx

Add tab index to more/less button which is displayed for audio entries with a long description
Resolves FEC-14146

fix(FEC-14146): Player v7 | For audio entries there is no option to tab navigate to the "More/Less" buttons under the description. 

---

src/reducers/shell.ts

I made playerNav default true, so that the keyboard navigation is activated from the first tab;
**Issue:**
**Fix:**
[ADA-1404]: https://kaltura.atlassian.net/browse/ADA-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1404): Add focus indicator to the first focusable element

---

src/components/play-pause/play-pause.tsx
src/components/seekbar/seekbar.tsx
src/components/tooltip/_tooltip.scss

issue:
when trying to play/pause a video in a small /extra small /tiny width player using voiceover on mac, the play/pause button disappears after a couple of seconds and the user is unable to pause or play the video again.
fix:
since play/pause button is not in the bottom bar in these widths, switch the focus on the seekbar, which will enable the play/pause functionality.
width <= 480:
width > 480:

fix(ADA-1593): shift focus to seekbar when playing/pausing media within small width players

---

src/components/tooltip/tooltip.tsx

**Issue:**
When focusing on control the tooltip is shown and is not gone until you move to another element.
**Fix:**
When click on Escape key the tooltip will disappear.
[ADA-1633]: https://kaltura.atlassian.net/browse/ADA-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1633): The tooltips for a player controls are not dismissible using the Esc key

---

src/components/advanced-audio-desc-toggle/advanced-audio-desc-toggle.tsx
src/components/advanced-audio-desc/advanced-audio-desc.tsx
translations/en.i18n.json

Updated advanced audio description text according to product, and change the label according to the button state
Resolves FEC-14141

fix(FEC-14141): Player v7 | For AAD bottom bar button, screen readers doesn't give indication if its on or off when user tab navigate to it.

---

src/reducers/shell.ts

Revert https://github.com/kaltura/playkit-js-ui/commit/bd09056adb2c3db9f9604c1f07d94ad9b1c04f1d, as it causes issues with button bar focus indication appearing when keyboard navigation is off

fix(FEC-14169): Player v7 | Two outlines blue and white appears using mouse navigation.

---

src/components/captions-control/captions-control-mini.tsx
src/components/captions-control/captions-control.tsx
src/components/overlay-portal/index.ts
src/components/overlay-portal/overlay-portal-utils.ts
src/components/overlay/overlay.tsx
src/components/settings/settings.tsx
src/components/smart-container/smart-container.tsx
src/index.ts

bugfix
**Issue:**
when opening the cvaa (advanced captions settings) while the video is playing and the video reaches a quiz question cue point, then closing the cvaa overlay- the quiz question overlay stays on the player and there is no way to close it.
the root cause is that closing the cvaa causes the removal of overlay-active class, which causes the odd behavior of the quiz question overlay.
**Fix:**
- do not remove the `overlay-active` class if `overlayPortal` component has multiple children- remove it only if there's a single child
- create a reusable `getOverlayPortalElement` function which returns the `overlayPortal` element
- use `getOverlayPortalElement` function in other components
- expose `getOverlayPortalElement` function for a future use outside of core scope

fix(FEC-14156): quiz overlay behind cvaa freezes

---

src/components/overlay/overlay.tsx

bugfix
**Issue:**
`overlay-active` class is not being removed from the player, which prevents any user interaction with the player.
in this specific case, `welcomeScreen` of quiz is an `Overlay` component but is not rendered under `OverlayPortal` - which breaks the current condition to remove the `overlay-active` class.
**Fix:**
add a new prop - `dontCheckOverlayPortal`, which indicates whether `Overlay` should go through the `OverlayPortal` condition, or simply remove `overlay-active` class unconditionally.
**related pr:** https://github.com/kaltura/playkit-js-ivq/pull/136

fix(FEC-14172): overlay-active is not removed from player

---

src/components/expandable-text/expandable-text.tsx

**Issue:**
screen reader doesn't announce the "Read more" button in Firefox browser
**Fix:**
Adding role button to div element.
[ADA-1789]: https://kaltura.atlassian.net/browse/ADA-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1789): [ORS] - Firefox playerkit - "Read more" button in the navigation overlay is not read by screen reader (NVDA)

---

src/components/play-pause/play-pause.tsx
src/components/pre-playback-play-overlay/pre-playback-play-overlay.tsx
translations/en.i18n.json

**Issue:**
When multiple players are embedded in single page, the screen reader's element list does not identify which button related to which player.
**Fix:**
Adding the entry name to the aria-label of play, pause, start over buttons
[ADA-17]: https://kaltura.atlassian.net/browse/ADA-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-17): Playback button labels are generic and not video specific

---

src/components/copy-button/copy-button.tsx

**Issue:**
Copy button doesn't have aria-label
**Fix:**
Adding aria-label on copy button
[ADA-1942]: https://kaltura.atlassian.net/browse/ADA-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1942): [University of Illinois] Missing Accessible Name for Copy Button

---

src/components/advanced-audio-desc/advanced-audio-desc.tsx
src/components/picture-in-picture/picture-in-picture.tsx
src/components/vr-stereo/vr-stereo.tsx

**bugfix**
**Issue:**
when `AAD` and `PiP` buttons are in the top bar- hitting space or enter keyboard does nothing.
**Fix:**
- add `onKeyDown` event listener to `AAD` and `PiP` components
- include `space` keyboard for `VR` component

fix(FEC-14177): a11y fixes

---

src/components/overlay/overlay.tsx

Issue:
Errors are not announced by the SR in case they pop up
Fix:
Adding aria-live and role alert in case we have a type error overlay
Resolves: https://kaltura.atlassian.net/browse/ADA-1742

fix(ADA-1742): When errors pops up they will also be announced by SR

---

src/components/seekbar/seekbar.tsx
translations/de.i18n.json
translations/en.i18n.json

**Issue:**
In non English languages the time is always time **of** time with no translation.
**Fix:**
Adding translations to "of" word
related to https://github.com/kaltura/playkit-js-ui/pull/955
[ADA-1791]: https://kaltura.atlassian.net/browse/ADA-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1791): [ORS] - Player - Screen reader (NVDA) is interpreting time values as clock times

---

src/components/error-overlay/error-message-provider.ts
translations/en.i18n.json

Adding error messages to site restriction and scheduled restriction
Part of - https://github.com/kaltura/playkit-js/pull/805, https://github.com/kaltura/kaltura-player-js/pull/897, https://github.com/kaltura/playkit-js-providers/pull/245
[SUP-45003]: https://kaltura.atlassian.net/browse/SUP-45003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-45003): [IKEA Ingka] - past scheduled embedded entries will show a wrong error message for V7 player

---

src/utils/popup-keyboard-accessibility.tsx

**Issue:** 
if user open the info plugin from more plugin, when press enter on x the focus is lost and doesn't move to the more plugin
**Root cause:**
The previous element is the dropdown info div from the more dropdown and not the the more button
**Fix:**
Create a reference of more plugin (we set it from the info plugin) and in case the previous element is dropdown item (of the more), move the focus to more plugin.
part of:
https://github.com/kaltura/playkit-js-ui-managers/pull/67
https://github.com/kaltura/playkit-js-info/pull/106
[ADA-1451]: https://kaltura.atlassian.net/browse/ADA-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADA(ADA-1451): Close Video Info modal dialog focus management

---

src/components/watermark/watermark.tsx

Support logo link URLs with a dynamic link that can change based on entry ID in the watermark link.
**Issue:**
https://kaltura.atlassian.net/browse/FEC-13837
**Fix:**
Added support for {entryId} in link address for watermark.

feat(FEC-13837): Add dynamic link support

---

src/components/error-overlay/error-overlay.tsx

After player had network disconnection error and user clicked on 'Try Again', player stucks with 'overlay: true'.
We need to update to 'overlay: false'.
Resolves [FEC-14289](https://kaltura.atlassian.net/browse/FEC-14289)
[FEC-14289]: https://kaltura.atlassian.net/browse/FEC-14289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14289): Player v7 | Player doesn't recover well after network disconnection

---

src/components/shell/shell.tsx

Issue: 
When browser width is small, side pannel is on, and enter full screen, there is a gap between side pannel and player.
Fix:
Fix timing issue : the issue related to the timing of the DOM updates. When resizing the window or triggering an actions that affect the layout, the client rect of the player container getBoundingClientRect() is not updated immediately after the resize. This causes discrepancies between the actual layout and the values being used in the state.
solved [SUP-46391](https://kaltura.atlassian.net/browse/SUP-46391)
[SUP-46391]: https://kaltura.atlassian.net/browse/SUP-46391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-46391): Player Live Full Screen Bug when browser window is not maximized

---

src/components/bottom-bar/bottom-bar.tsx
src/components/seekbar/seekbar.tsx
src/components/shell/shell.tsx
src/event/event-type.ts
src/event/events/bottom-bar-client-rect-event.ts

**Issue:**
Timing issue: in some cases the delay in the setTimeOut in SeekBar.tsx file is not enough, and the bottomBarClientRect in BottomBar.tsx being updated too late, just after the set time out scope is being executed. This affects the seekBar width, which creates a problem with position the cue-points on the seekBar.
**Fix:**
Add an event that will update the seekBar every time the bottomBarClientRect is being updated. The seekBar.tsx will always get the most updated width.
solved-[SUP-46685](https://kaltura.atlassian.net/browse/SUP-46685)
[SUP-46685]: https://kaltura.atlassian.net/browse/SUP-46685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-46685): Multiple Chapters in Quiz Break the Timeline

---

src/components/shell/shell.tsx

bugfix, regression from [fix](https://github.com/kaltura/playkit-js-ui/pull/982).
**Issue:**
player crushes when executing `updatePlayerClientRect` with an undefined `playerContainer`.
**Fix:**
execute `updatePlayerClientRect` only if `playerContainer` exists.

fix(CR-317): player crushes on reload

---

webpack.config.js

add `nonce` attribute to the style tag pushed to DOM.
- override the default `insert` behavior of `style-loader`
- if `nonce` exists- add it to the style element

feat(FEC-14367): add nonce to style tag

---

src/components/watermark/_watermark.scss
src/components/watermark/watermark.tsx

**Issue:**
Currently when client applies a watermark image, it is just applied on the player "as is" without calculate the proportion considering the player height and width.
**Fix:**
Calculate the aspect ratio of the image, and apply new height and width based on the player size.
Listen to resize event and update the image size whenever resize is being dispatched.
solved https://kaltura.atlassian.net/browse/SUP-47338

fix (SUP-47338): Watermark On Player Not Responsive

---

src/components/cvaa-overlay/cvaa-overlay.tsx
src/components/overlay/overlay.tsx
translations/en.i18n.json

This solves this https://kaltura.atlassian.net/browse/ADA-2122. It includes the modal title to the Advanced captions settings modal's close button.
This should be merged after this https://github.com/kaltura/playkit-js-ui/pull/984
**Issue:**
**Fix:**

fix(ADA-2122): Include modal title in close button aria-label

---

src/components/overlay/overlay.tsx

This solves https://kaltura.atlassian.net/browse/ADA-1745
Related to  https://github.com/kaltura/playkit-js-info/pull/112 and https://github.com/kaltura/playkit-js-downloads/pull/84
**Issue:**
**Fix:**

fix(ADA-1745) - Create alternative aria-label for close button 

---

src/components/playback-controls/_playback-controls.scss
src/components/playback-controls/playback-controls.tsx

issue:
on small sizes with image play/pause button can be seen on screen
root- cause
there is css style for the play/pause icon for small sizes
solution:
check if it image, then add class to make css not be implemented
solve [SUP-47502](https://kaltura.atlassian.net/browse/SUP-47502)
[SUP-47502]: https://kaltura.atlassian.net/browse/SUP-47502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-47502): Play/Pause button on images in embed

---

src/components/side-panel/_side-panel.scss

bugfix.
**Issue:**
youtube overlay has z-index which overlays the kitchen sink of the side panel when the `expandMode` is `over`.
**Fix:**
increase `z-index` of sidePanel component to `1`.
**Note:**
`z-index` of sidePanel was decreased to `0` following this [commit](https://github.com/kaltura/playkit-js-ui/commit/e3fa3c6cff9c407c0efea847cae7bae4487fab6a); i've tested this issue with `z-index: 1` to make sure we are avoiding regression; works well with both expand modes `over` and `alongSide`.

fix(FEC-14421): For youtube entries, kitchen sink isn't visible when opening summary plugin with "expandMode": "over"

---

src/components/shell/shell.tsx

**Issue:**
When open the player, press tab until it focuses on any button in the video other than fullscreen, when press F should trigger the fullscreen.
**Fix:**
handle a case of F (for fullscreen) when tabbing.
fix [SUP-47965](https://kaltura.atlassian.net/browse/SUP-47965)
[SUP-47965]: https://kaltura.atlassian.net/browse/SUP-47965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix (SUP-47965): Hotkey F is not working when the focus is on another button in the video.

---

src/components/fullscreen/fullscreen.tsx
src/components/shell/shell.tsx

**Issue:**
On text box, when navigate to the text box with tab, and press F it opens the fullscreen mode instead write the letter 'f'
**Fix:**
In a case of text area or input or any text box, ignore the hotkey F.
solved [SUP-47965](https://kaltura.atlassian.net/browse/SUP-47965)
[SUP-47965]: https://kaltura.atlassian.net/browse/SUP-47965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix (SUP-47965): Hotkey F is not working when the focus is on another button in the video

---

src/components/error-overlay/error-message-provider.ts
translations/en.i18n.json

**Issue:**
Blocked Access Control error is not supported.
**Fix:**
Add support to new Error type
solved [SUP-48028](https://kaltura.atlassian.net/browse/SUP-48028)
related PRS:
https://github.com/kaltura/kaltura-player-js/pull/967
https://github.com/kaltura/playkit-js/pull/816
[SUP-48028]: https://kaltura.atlassian.net/browse/SUP-48028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: (SUP-48028): Player V7 does not display access control message

---

src/components/context-menu/_context-menu.scss
src/components/context-menu/context-menu.tsx
src/styles/style.scss

1. render context menu in portal. Position of context menu sets relative to document.body;
2. use custom context menu and browser native context menu (approach taken from youtube). If custom context menu opened next right-button click trigger appearing of native context menu;
Resolves https://kaltura.atlassian.net/browse/FEC-14445;

fix(FEC-14445): fix position of context menu

---

src/components/volume/volume.tsx
translations/en.i18n.json

This solves this https://github.com/kaltura/playkit-js-ui/pull/1023 replacing the description from aria-label. For the description i am using aria-description
**Issue:**
**Fix:**

fix(ADA-2794): Remove description from aria-label

---

src/components/context-menu/_context-menu.scss
src/components/context-menu/context-menu-utils.ts
src/components/context-menu/context-menu.tsx
src/styles/_variables.scss

Handle debug info context menu in iOS:
- use touch events instead of contextmenu event, which doesnt fire in iOS
- protect against navigator.clipboard.writeText not working in iOS under certain conditions (for example, it works in some iframe pages but doesn't work in others)
Resolves FEC-14497

fix(FEC-14497): Add Debug Info Option to the Player | Long pressing on ios mobile doesnt show "Copy debug info" button".

---

src/components/bottom-bar/_bottom-bar.scss
src/components/time-display/_time-display.scss

- per Designer request - align the bottom bar controls' gap to `8px` instead of `12px`.
- change the padding for `time-display` component, to match the requirement

fix(FEC-14273): change gap between bottom bar controls

---

src/components/unmute-indication/_unmute-indication.scss
src/components/unmute-indication/unmute-indication.tsx
src/styles/_variables.scss
src/ui-presets/playback.tsx

**Issue:**
`Unmute indicator` button overlaps top-bar left controls.
**Fix:**
- align current appearance of `unmute` component with design
- for `playback` preset move `unmute` component to `interactive-area` - other presets do not have controls in the top-bar left area

fix(FEC-14482): Unmute button overlaps top bar controls

---

src/components/captions-control/captions-control-mini.tsx
src/components/captions-control/captions-control.tsx
src/components/closed-captions/closed-captions.tsx
src/utils/key-map.ts

**Issue:**
When CC button display on upper bar outside of more plugins, open it with spacebar \ enter doesnt work.
**Fix:**
- Added keyboard event handlers to CC button components to respond to Enter and Space key presses
- Fixed accessibility issue where CC buttons in the upper toolbar weren't keyboard-activatable
- Implemented consistent keyboard handling across all three CC-related components (ClosedCaptions, CaptionsControl, CaptionsControlMini)
[FEC-14449](https://kaltura.atlassian.net/browse/FEC-14449)
[FEC-14449]: https://kaltura.atlassian.net/browse/FEC-14449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14449): When CC button display on upper bar outside of more plugins, open it with spacebar \ enter doesnt work

---

src/components/context-menu/context-menu-utils.ts
src/components/context-menu/context-menu.tsx
src/event/event-type.ts

Add analytics for Copy Debug Info
Related PR: https://github.com/kaltura/playkit-js-kava/pull/203
[FEC-14520](https://kaltura.atlassian.net/browse/FEC-14520)
[FEC-14520]: https://kaltura.atlassian.net/browse/FEC-14520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FEC-14520): Add analytics for Copy Debug Info

---

translations/pt_br.i18n.json

Remove duplicated translations for secondsRewind and secondsForward in Portuguese file

fix(SUP-48552): Missing translation in player v7

---

src/components/menu/menu.tsx

**Issue:**
In case dropdown under settings (audio, captions) has many items, the most top item is not clickable because top-bar element overlapping it.
**Fix:**
Change the max-height value by subtract the top-bar and the bottom-bar height.
[SUP-48894]: https://kaltura.atlassian.net/browse/SUP-48894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-48894): Audio flavor selector bug

---

src/components/error-overlay/error-message-provider.ts
translations/en.i18n.json

Adding error messages for moderation restriction
Part of https://github.com/kaltura/playkit-js-providers/pull/265, https://github.com/kaltura/playkit-js/pull/822, https://github.com/kaltura/playkit-js-ui/pull/1053
[SUP-48817]: https://kaltura.atlassian.net/browse/SUP-48817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-48817): Entries Under Moderation Are Still Playing

---

src/components/pre-playback-play-overlay/pre-playback-play-overlay.tsx

Add protection in case sources do not contain capabilities array
This can happen when using setMedia or in certain scenarios in kms
Resolves FEC-14623

fix(FEC-14623): Player v7 | Player controls are missing on kms with theming enabled.

---

src/styles/_buttons.scss

Reverting https://github.com/kaltura/playkit-js-ui/pull/1066 because it caused https://kaltura.atlassian.net/browse/FEC-14634
**Issue:**
**Fix:**

Revert "fix(FEC-14593): Add focus indicator to button component"
